// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tradex/internal/infra/ent/backtestresult"
	"tradex/internal/infra/ent/backtesttask"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BacktestTaskCreate is the builder for creating a BacktestTask entity.
type BacktestTaskCreate struct {
	config
	mutation *BacktestTaskMutation
	hooks    []Hook
}

// SetStrategyID sets the "strategy_id" field.
func (_c *BacktestTaskCreate) SetStrategyID(v uuid.UUID) *BacktestTaskCreate {
	_c.mutation.SetStrategyID(v)
	return _c
}

// SetStrategyName sets the "strategy_name" field.
func (_c *BacktestTaskCreate) SetStrategyName(v string) *BacktestTaskCreate {
	_c.mutation.SetStrategyName(v)
	return _c
}

// SetNillableStrategyName sets the "strategy_name" field if the given value is not nil.
func (_c *BacktestTaskCreate) SetNillableStrategyName(v *string) *BacktestTaskCreate {
	if v != nil {
		_c.SetStrategyName(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *BacktestTaskCreate) SetCreatedBy(v uuid.UUID) *BacktestTaskCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *BacktestTaskCreate) SetNillableCreatedBy(v *uuid.UUID) *BacktestTaskCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetExchangeID sets the "exchange_id" field.
func (_c *BacktestTaskCreate) SetExchangeID(v uuid.UUID) *BacktestTaskCreate {
	_c.mutation.SetExchangeID(v)
	return _c
}

// SetPair sets the "pair" field.
func (_c *BacktestTaskCreate) SetPair(v string) *BacktestTaskCreate {
	_c.mutation.SetPair(v)
	return _c
}

// SetTimeframe sets the "timeframe" field.
func (_c *BacktestTaskCreate) SetTimeframe(v string) *BacktestTaskCreate {
	_c.mutation.SetTimeframe(v)
	return _c
}

// SetInitialCapital sets the "initial_capital" field.
func (_c *BacktestTaskCreate) SetInitialCapital(v float64) *BacktestTaskCreate {
	_c.mutation.SetInitialCapital(v)
	return _c
}

// SetPositionSize sets the "position_size" field.
func (_c *BacktestTaskCreate) SetPositionSize(v float64) *BacktestTaskCreate {
	_c.mutation.SetPositionSize(v)
	return _c
}

// SetNillablePositionSize sets the "position_size" field if the given value is not nil.
func (_c *BacktestTaskCreate) SetNillablePositionSize(v *float64) *BacktestTaskCreate {
	if v != nil {
		_c.SetPositionSize(*v)
	}
	return _c
}

// SetStartAt sets the "start_at" field.
func (_c *BacktestTaskCreate) SetStartAt(v time.Time) *BacktestTaskCreate {
	_c.mutation.SetStartAt(v)
	return _c
}

// SetEndAt sets the "end_at" field.
func (_c *BacktestTaskCreate) SetEndAt(v time.Time) *BacktestTaskCreate {
	_c.mutation.SetEndAt(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *BacktestTaskCreate) SetCompletedAt(v time.Time) *BacktestTaskCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *BacktestTaskCreate) SetNillableCompletedAt(v *time.Time) *BacktestTaskCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BacktestTaskCreate) SetStatus(v backtesttask.Status) *BacktestTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BacktestTaskCreate) SetNillableStatus(v *backtesttask.Status) *BacktestTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPhase sets the "phase" field.
func (_c *BacktestTaskCreate) SetPhase(v backtesttask.Phase) *BacktestTaskCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *BacktestTaskCreate) SetNillablePhase(v *backtesttask.Phase) *BacktestTaskCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BacktestTaskCreate) SetCreatedAt(v time.Time) *BacktestTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BacktestTaskCreate) SetNillableCreatedAt(v *time.Time) *BacktestTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BacktestTaskCreate) SetID(v uuid.UUID) *BacktestTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BacktestTaskCreate) SetNillableID(v *uuid.UUID) *BacktestTaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetResultID sets the "result" edge to the BacktestResult entity by ID.
func (_c *BacktestTaskCreate) SetResultID(id uuid.UUID) *BacktestTaskCreate {
	_c.mutation.SetResultID(id)
	return _c
}

// SetNillableResultID sets the "result" edge to the BacktestResult entity by ID if the given value is not nil.
func (_c *BacktestTaskCreate) SetNillableResultID(id *uuid.UUID) *BacktestTaskCreate {
	if id != nil {
		_c = _c.SetResultID(*id)
	}
	return _c
}

// SetResult sets the "result" edge to the BacktestResult entity.
func (_c *BacktestTaskCreate) SetResult(v *BacktestResult) *BacktestTaskCreate {
	return _c.SetResultID(v.ID)
}

// Mutation returns the BacktestTaskMutation object of the builder.
func (_c *BacktestTaskCreate) Mutation() *BacktestTaskMutation {
	return _c.mutation
}

// Save creates the BacktestTask in the database.
func (_c *BacktestTaskCreate) Save(ctx context.Context) (*BacktestTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BacktestTaskCreate) SaveX(ctx context.Context) *BacktestTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BacktestTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BacktestTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BacktestTaskCreate) defaults() {
	if _, ok := _c.mutation.StrategyName(); !ok {
		v := backtesttask.DefaultStrategyName
		_c.mutation.SetStrategyName(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := backtesttask.DefaultCreatedBy()
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := backtesttask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := backtesttask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := backtesttask.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BacktestTaskCreate) check() error {
	if _, ok := _c.mutation.StrategyID(); !ok {
		return &ValidationError{Name: "strategy_id", err: errors.New(`ent: missing required field "BacktestTask.strategy_id"`)}
	}
	if _, ok := _c.mutation.StrategyName(); !ok {
		return &ValidationError{Name: "strategy_name", err: errors.New(`ent: missing required field "BacktestTask.strategy_name"`)}
	}
	if v, ok := _c.mutation.StrategyName(); ok {
		if err := backtesttask.StrategyNameValidator(v); err != nil {
			return &ValidationError{Name: "strategy_name", err: fmt.Errorf(`ent: validator failed for field "BacktestTask.strategy_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "BacktestTask.created_by"`)}
	}
	if _, ok := _c.mutation.ExchangeID(); !ok {
		return &ValidationError{Name: "exchange_id", err: errors.New(`ent: missing required field "BacktestTask.exchange_id"`)}
	}
	if _, ok := _c.mutation.Pair(); !ok {
		return &ValidationError{Name: "pair", err: errors.New(`ent: missing required field "BacktestTask.pair"`)}
	}
	if v, ok := _c.mutation.Pair(); ok {
		if err := backtesttask.PairValidator(v); err != nil {
			return &ValidationError{Name: "pair", err: fmt.Errorf(`ent: validator failed for field "BacktestTask.pair": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timeframe(); !ok {
		return &ValidationError{Name: "timeframe", err: errors.New(`ent: missing required field "BacktestTask.timeframe"`)}
	}
	if v, ok := _c.mutation.Timeframe(); ok {
		if err := backtesttask.TimeframeValidator(v); err != nil {
			return &ValidationError{Name: "timeframe", err: fmt.Errorf(`ent: validator failed for field "BacktestTask.timeframe": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InitialCapital(); !ok {
		return &ValidationError{Name: "initial_capital", err: errors.New(`ent: missing required field "BacktestTask.initial_capital"`)}
	}
	if _, ok := _c.mutation.StartAt(); !ok {
		return &ValidationError{Name: "start_at", err: errors.New(`ent: missing required field "BacktestTask.start_at"`)}
	}
	if _, ok := _c.mutation.EndAt(); !ok {
		return &ValidationError{Name: "end_at", err: errors.New(`ent: missing required field "BacktestTask.end_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BacktestTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := backtesttask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BacktestTask.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Phase(); ok {
		if err := backtesttask.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "BacktestTask.phase": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BacktestTask.created_at"`)}
	}
	return nil
}

func (_c *BacktestTaskCreate) sqlSave(ctx context.Context) (*BacktestTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BacktestTaskCreate) createSpec() (*BacktestTask, *sqlgraph.CreateSpec) {
	var (
		_node = &BacktestTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(backtesttask.Table, sqlgraph.NewFieldSpec(backtesttask.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.StrategyID(); ok {
		_spec.SetField(backtesttask.FieldStrategyID, field.TypeUUID, value)
		_node.StrategyID = value
	}
	if value, ok := _c.mutation.StrategyName(); ok {
		_spec.SetField(backtesttask.FieldStrategyName, field.TypeString, value)
		_node.StrategyName = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(backtesttask.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.ExchangeID(); ok {
		_spec.SetField(backtesttask.FieldExchangeID, field.TypeUUID, value)
		_node.ExchangeID = value
	}
	if value, ok := _c.mutation.Pair(); ok {
		_spec.SetField(backtesttask.FieldPair, field.TypeString, value)
		_node.Pair = value
	}
	if value, ok := _c.mutation.Timeframe(); ok {
		_spec.SetField(backtesttask.FieldTimeframe, field.TypeString, value)
		_node.Timeframe = value
	}
	if value, ok := _c.mutation.InitialCapital(); ok {
		_spec.SetField(backtesttask.FieldInitialCapital, field.TypeFloat64, value)
		_node.InitialCapital = value
	}
	if value, ok := _c.mutation.PositionSize(); ok {
		_spec.SetField(backtesttask.FieldPositionSize, field.TypeFloat64, value)
		_node.PositionSize = &value
	}
	if value, ok := _c.mutation.StartAt(); ok {
		_spec.SetField(backtesttask.FieldStartAt, field.TypeTime, value)
		_node.StartAt = value
	}
	if value, ok := _c.mutation.EndAt(); ok {
		_spec.SetField(backtesttask.FieldEndAt, field.TypeTime, value)
		_node.EndAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(backtesttask.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(backtesttask.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(backtesttask.FieldPhase, field.TypeEnum, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(backtesttask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ResultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   backtesttask.ResultTable,
			Columns: []string{backtesttask.ResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backtestresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BacktestTaskCreateBulk is the builder for creating many BacktestTask entities in bulk.
type BacktestTaskCreateBulk struct {
	config
	err      error
	builders []*BacktestTaskCreate
}

// Save creates the BacktestTask entities in the database.
func (_c *BacktestTaskCreateBulk) Save(ctx context.Context) ([]*BacktestTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BacktestTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BacktestTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BacktestTaskCreateBulk) SaveX(ctx context.Context) []*BacktestTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BacktestTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BacktestTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
