// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tradex/internal/infra/ent/exchange"
	"tradex/internal/infra/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ExchangeUpdate is the builder for updating Exchange entities.
type ExchangeUpdate struct {
	config
	hooks    []Hook
	mutation *ExchangeMutation
}

// Where appends a list predicates to the ExchangeUpdate builder.
func (_u *ExchangeUpdate) Where(ps ...predicate.Exchange) *ExchangeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ExchangeUpdate) SetName(v string) *ExchangeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ExchangeUpdate) SetNillableName(v *string) *ExchangeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ExchangeUpdate) SetType(v string) *ExchangeUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ExchangeUpdate) SetNillableType(v *string) *ExchangeUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_u *ExchangeUpdate) SetAPIKeyEncrypted(v string) *ExchangeUpdate {
	_u.mutation.SetAPIKeyEncrypted(v)
	return _u
}

// SetNillableAPIKeyEncrypted sets the "api_key_encrypted" field if the given value is not nil.
func (_u *ExchangeUpdate) SetNillableAPIKeyEncrypted(v *string) *ExchangeUpdate {
	if v != nil {
		_u.SetAPIKeyEncrypted(*v)
	}
	return _u
}

// SetSecretKeyEncrypted sets the "secret_key_encrypted" field.
func (_u *ExchangeUpdate) SetSecretKeyEncrypted(v string) *ExchangeUpdate {
	_u.mutation.SetSecretKeyEncrypted(v)
	return _u
}

// SetNillableSecretKeyEncrypted sets the "secret_key_encrypted" field if the given value is not nil.
func (_u *ExchangeUpdate) SetNillableSecretKeyEncrypted(v *string) *ExchangeUpdate {
	if v != nil {
		_u.SetSecretKeyEncrypted(*v)
	}
	return _u
}

// SetPassphraseEncrypted sets the "passphrase_encrypted" field.
func (_u *ExchangeUpdate) SetPassphraseEncrypted(v string) *ExchangeUpdate {
	_u.mutation.SetPassphraseEncrypted(v)
	return _u
}

// SetNillablePassphraseEncrypted sets the "passphrase_encrypted" field if the given value is not nil.
func (_u *ExchangeUpdate) SetNillablePassphraseEncrypted(v *string) *ExchangeUpdate {
	if v != nil {
		_u.SetPassphraseEncrypted(*v)
	}
	return _u
}

// ClearPassphraseEncrypted clears the value of the "passphrase_encrypted" field.
func (_u *ExchangeUpdate) ClearPassphraseEncrypted() *ExchangeUpdate {
	_u.mutation.ClearPassphraseEncrypted()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ExchangeUpdate) SetStatus(v string) *ExchangeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExchangeUpdate) SetNillableStatus(v *string) *ExchangeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastTestedAt sets the "last_tested_at" field.
func (_u *ExchangeUpdate) SetLastTestedAt(v time.Time) *ExchangeUpdate {
	_u.mutation.SetLastTestedAt(v)
	return _u
}

// SetNillableLastTestedAt sets the "last_tested_at" field if the given value is not nil.
func (_u *ExchangeUpdate) SetNillableLastTestedAt(v *time.Time) *ExchangeUpdate {
	if v != nil {
		_u.SetLastTestedAt(*v)
	}
	return _u
}

// ClearLastTestedAt clears the value of the "last_tested_at" field.
func (_u *ExchangeUpdate) ClearLastTestedAt() *ExchangeUpdate {
	_u.mutation.ClearLastTestedAt()
	return _u
}

// SetTestResult sets the "test_result" field.
func (_u *ExchangeUpdate) SetTestResult(v string) *ExchangeUpdate {
	_u.mutation.SetTestResult(v)
	return _u
}

// SetNillableTestResult sets the "test_result" field if the given value is not nil.
func (_u *ExchangeUpdate) SetNillableTestResult(v *string) *ExchangeUpdate {
	if v != nil {
		_u.SetTestResult(*v)
	}
	return _u
}

// ClearTestResult clears the value of the "test_result" field.
func (_u *ExchangeUpdate) ClearTestResult() *ExchangeUpdate {
	_u.mutation.ClearTestResult()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ExchangeUpdate) SetCreatedBy(v uuid.UUID) *ExchangeUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ExchangeUpdate) SetNillableCreatedBy(v *uuid.UUID) *ExchangeUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExchangeUpdate) SetUpdatedAt(v time.Time) *ExchangeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExchangeMutation object of the builder.
func (_u *ExchangeUpdate) Mutation() *ExchangeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExchangeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExchangeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExchangeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExchangeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExchangeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := exchange.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ExchangeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(exchange.Table, exchange.Columns, sqlgraph.NewFieldSpec(exchange.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(exchange.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(exchange.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(exchange.FieldAPIKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKeyEncrypted(); ok {
		_spec.SetField(exchange.FieldSecretKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassphraseEncrypted(); ok {
		_spec.SetField(exchange.FieldPassphraseEncrypted, field.TypeString, value)
	}
	if _u.mutation.PassphraseEncryptedCleared() {
		_spec.ClearField(exchange.FieldPassphraseEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(exchange.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastTestedAt(); ok {
		_spec.SetField(exchange.FieldLastTestedAt, field.TypeTime, value)
	}
	if _u.mutation.LastTestedAtCleared() {
		_spec.ClearField(exchange.FieldLastTestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TestResult(); ok {
		_spec.SetField(exchange.FieldTestResult, field.TypeString, value)
	}
	if _u.mutation.TestResultCleared() {
		_spec.ClearField(exchange.FieldTestResult, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(exchange.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(exchange.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exchange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExchangeUpdateOne is the builder for updating a single Exchange entity.
type ExchangeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExchangeMutation
}

// SetName sets the "name" field.
func (_u *ExchangeUpdateOne) SetName(v string) *ExchangeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ExchangeUpdateOne) SetNillableName(v *string) *ExchangeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ExchangeUpdateOne) SetType(v string) *ExchangeUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ExchangeUpdateOne) SetNillableType(v *string) *ExchangeUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_u *ExchangeUpdateOne) SetAPIKeyEncrypted(v string) *ExchangeUpdateOne {
	_u.mutation.SetAPIKeyEncrypted(v)
	return _u
}

// SetNillableAPIKeyEncrypted sets the "api_key_encrypted" field if the given value is not nil.
func (_u *ExchangeUpdateOne) SetNillableAPIKeyEncrypted(v *string) *ExchangeUpdateOne {
	if v != nil {
		_u.SetAPIKeyEncrypted(*v)
	}
	return _u
}

// SetSecretKeyEncrypted sets the "secret_key_encrypted" field.
func (_u *ExchangeUpdateOne) SetSecretKeyEncrypted(v string) *ExchangeUpdateOne {
	_u.mutation.SetSecretKeyEncrypted(v)
	return _u
}

// SetNillableSecretKeyEncrypted sets the "secret_key_encrypted" field if the given value is not nil.
func (_u *ExchangeUpdateOne) SetNillableSecretKeyEncrypted(v *string) *ExchangeUpdateOne {
	if v != nil {
		_u.SetSecretKeyEncrypted(*v)
	}
	return _u
}

// SetPassphraseEncrypted sets the "passphrase_encrypted" field.
func (_u *ExchangeUpdateOne) SetPassphraseEncrypted(v string) *ExchangeUpdateOne {
	_u.mutation.SetPassphraseEncrypted(v)
	return _u
}

// SetNillablePassphraseEncrypted sets the "passphrase_encrypted" field if the given value is not nil.
func (_u *ExchangeUpdateOne) SetNillablePassphraseEncrypted(v *string) *ExchangeUpdateOne {
	if v != nil {
		_u.SetPassphraseEncrypted(*v)
	}
	return _u
}

// ClearPassphraseEncrypted clears the value of the "passphrase_encrypted" field.
func (_u *ExchangeUpdateOne) ClearPassphraseEncrypted() *ExchangeUpdateOne {
	_u.mutation.ClearPassphraseEncrypted()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ExchangeUpdateOne) SetStatus(v string) *ExchangeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExchangeUpdateOne) SetNillableStatus(v *string) *ExchangeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastTestedAt sets the "last_tested_at" field.
func (_u *ExchangeUpdateOne) SetLastTestedAt(v time.Time) *ExchangeUpdateOne {
	_u.mutation.SetLastTestedAt(v)
	return _u
}

// SetNillableLastTestedAt sets the "last_tested_at" field if the given value is not nil.
func (_u *ExchangeUpdateOne) SetNillableLastTestedAt(v *time.Time) *ExchangeUpdateOne {
	if v != nil {
		_u.SetLastTestedAt(*v)
	}
	return _u
}

// ClearLastTestedAt clears the value of the "last_tested_at" field.
func (_u *ExchangeUpdateOne) ClearLastTestedAt() *ExchangeUpdateOne {
	_u.mutation.ClearLastTestedAt()
	return _u
}

// SetTestResult sets the "test_result" field.
func (_u *ExchangeUpdateOne) SetTestResult(v string) *ExchangeUpdateOne {
	_u.mutation.SetTestResult(v)
	return _u
}

// SetNillableTestResult sets the "test_result" field if the given value is not nil.
func (_u *ExchangeUpdateOne) SetNillableTestResult(v *string) *ExchangeUpdateOne {
	if v != nil {
		_u.SetTestResult(*v)
	}
	return _u
}

// ClearTestResult clears the value of the "test_result" field.
func (_u *ExchangeUpdateOne) ClearTestResult() *ExchangeUpdateOne {
	_u.mutation.ClearTestResult()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ExchangeUpdateOne) SetCreatedBy(v uuid.UUID) *ExchangeUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ExchangeUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *ExchangeUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExchangeUpdateOne) SetUpdatedAt(v time.Time) *ExchangeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExchangeMutation object of the builder.
func (_u *ExchangeUpdateOne) Mutation() *ExchangeMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExchangeUpdate builder.
func (_u *ExchangeUpdateOne) Where(ps ...predicate.Exchange) *ExchangeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExchangeUpdateOne) Select(field string, fields ...string) *ExchangeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Exchange entity.
func (_u *ExchangeUpdateOne) Save(ctx context.Context) (*Exchange, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExchangeUpdateOne) SaveX(ctx context.Context) *Exchange {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExchangeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExchangeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExchangeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := exchange.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ExchangeUpdateOne) sqlSave(ctx context.Context) (_node *Exchange, err error) {
	_spec := sqlgraph.NewUpdateSpec(exchange.Table, exchange.Columns, sqlgraph.NewFieldSpec(exchange.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Exchange.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exchange.FieldID)
		for _, f := range fields {
			if !exchange.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exchange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(exchange.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(exchange.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(exchange.FieldAPIKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKeyEncrypted(); ok {
		_spec.SetField(exchange.FieldSecretKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassphraseEncrypted(); ok {
		_spec.SetField(exchange.FieldPassphraseEncrypted, field.TypeString, value)
	}
	if _u.mutation.PassphraseEncryptedCleared() {
		_spec.ClearField(exchange.FieldPassphraseEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(exchange.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastTestedAt(); ok {
		_spec.SetField(exchange.FieldLastTestedAt, field.TypeTime, value)
	}
	if _u.mutation.LastTestedAtCleared() {
		_spec.ClearField(exchange.FieldLastTestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TestResult(); ok {
		_spec.SetField(exchange.FieldTestResult, field.TypeString, value)
	}
	if _u.mutation.TestResultCleared() {
		_spec.ClearField(exchange.FieldTestResult, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(exchange.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(exchange.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Exchange{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exchange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
