// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tradex/internal/infra/ent/exchangeorderhistory"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ExchangeOrderHistoryCreate is the builder for creating a ExchangeOrderHistory entity.
type ExchangeOrderHistoryCreate struct {
	config
	mutation *ExchangeOrderHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetExchangeID sets the "exchange_id" field.
func (_c *ExchangeOrderHistoryCreate) SetExchangeID(v uuid.UUID) *ExchangeOrderHistoryCreate {
	_c.mutation.SetExchangeID(v)
	return _c
}

// SetPair sets the "pair" field.
func (_c *ExchangeOrderHistoryCreate) SetPair(v string) *ExchangeOrderHistoryCreate {
	_c.mutation.SetPair(v)
	return _c
}

// SetNillablePair sets the "pair" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillablePair(v *string) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetPair(*v)
	}
	return _c
}

// SetSide sets the "side" field.
func (_c *ExchangeOrderHistoryCreate) SetSide(v string) *ExchangeOrderHistoryCreate {
	_c.mutation.SetSide(v)
	return _c
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillableSide(v *string) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetSide(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ExchangeOrderHistoryCreate) SetType(v string) *ExchangeOrderHistoryCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillableType(v *string) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExchangeOrderHistoryCreate) SetStatus(v string) *ExchangeOrderHistoryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillableStatus(v *string) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *ExchangeOrderHistoryCreate) SetPrice(v float64) *ExchangeOrderHistoryCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillablePrice(v *float64) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *ExchangeOrderHistoryCreate) SetQuantity(v float64) *ExchangeOrderHistoryCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillableQuantity(v *float64) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetFilledQuantity sets the "filled_quantity" field.
func (_c *ExchangeOrderHistoryCreate) SetFilledQuantity(v float64) *ExchangeOrderHistoryCreate {
	_c.mutation.SetFilledQuantity(v)
	return _c
}

// SetNillableFilledQuantity sets the "filled_quantity" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillableFilledQuantity(v *float64) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetFilledQuantity(*v)
	}
	return _c
}

// SetExchangeOrderID sets the "exchange_order_id" field.
func (_c *ExchangeOrderHistoryCreate) SetExchangeOrderID(v string) *ExchangeOrderHistoryCreate {
	_c.mutation.SetExchangeOrderID(v)
	return _c
}

// SetNillableExchangeOrderID sets the "exchange_order_id" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillableExchangeOrderID(v *string) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetExchangeOrderID(*v)
	}
	return _c
}

// SetPlacedAt sets the "placed_at" field.
func (_c *ExchangeOrderHistoryCreate) SetPlacedAt(v time.Time) *ExchangeOrderHistoryCreate {
	_c.mutation.SetPlacedAt(v)
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *ExchangeOrderHistoryCreate) SetSyncedAt(v time.Time) *ExchangeOrderHistoryCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillableSyncedAt(v *time.Time) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExchangeOrderHistoryCreate) SetID(v uuid.UUID) *ExchangeOrderHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExchangeOrderHistoryCreate) SetNillableID(v *uuid.UUID) *ExchangeOrderHistoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ExchangeOrderHistoryMutation object of the builder.
func (_c *ExchangeOrderHistoryCreate) Mutation() *ExchangeOrderHistoryMutation {
	return _c.mutation
}

// Save creates the ExchangeOrderHistory in the database.
func (_c *ExchangeOrderHistoryCreate) Save(ctx context.Context) (*ExchangeOrderHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExchangeOrderHistoryCreate) SaveX(ctx context.Context) *ExchangeOrderHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeOrderHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeOrderHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExchangeOrderHistoryCreate) defaults() {
	if _, ok := _c.mutation.Pair(); !ok {
		v := exchangeorderhistory.DefaultPair
		_c.mutation.SetPair(v)
	}
	if _, ok := _c.mutation.Side(); !ok {
		v := exchangeorderhistory.DefaultSide
		_c.mutation.SetSide(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := exchangeorderhistory.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := exchangeorderhistory.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Price(); !ok {
		v := exchangeorderhistory.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		v := exchangeorderhistory.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.FilledQuantity(); !ok {
		v := exchangeorderhistory.DefaultFilledQuantity
		_c.mutation.SetFilledQuantity(v)
	}
	if _, ok := _c.mutation.ExchangeOrderID(); !ok {
		v := exchangeorderhistory.DefaultExchangeOrderID
		_c.mutation.SetExchangeOrderID(v)
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		v := exchangeorderhistory.DefaultSyncedAt()
		_c.mutation.SetSyncedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := exchangeorderhistory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExchangeOrderHistoryCreate) check() error {
	if _, ok := _c.mutation.ExchangeID(); !ok {
		return &ValidationError{Name: "exchange_id", err: errors.New(`ent: missing required field "ExchangeOrderHistory.exchange_id"`)}
	}
	if _, ok := _c.mutation.Pair(); !ok {
		return &ValidationError{Name: "pair", err: errors.New(`ent: missing required field "ExchangeOrderHistory.pair"`)}
	}
	if _, ok := _c.mutation.Side(); !ok {
		return &ValidationError{Name: "side", err: errors.New(`ent: missing required field "ExchangeOrderHistory.side"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ExchangeOrderHistory.type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ExchangeOrderHistory.status"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ExchangeOrderHistory.price"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "ExchangeOrderHistory.quantity"`)}
	}
	if _, ok := _c.mutation.FilledQuantity(); !ok {
		return &ValidationError{Name: "filled_quantity", err: errors.New(`ent: missing required field "ExchangeOrderHistory.filled_quantity"`)}
	}
	if _, ok := _c.mutation.ExchangeOrderID(); !ok {
		return &ValidationError{Name: "exchange_order_id", err: errors.New(`ent: missing required field "ExchangeOrderHistory.exchange_order_id"`)}
	}
	if _, ok := _c.mutation.PlacedAt(); !ok {
		return &ValidationError{Name: "placed_at", err: errors.New(`ent: missing required field "ExchangeOrderHistory.placed_at"`)}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "ExchangeOrderHistory.synced_at"`)}
	}
	return nil
}

func (_c *ExchangeOrderHistoryCreate) sqlSave(ctx context.Context) (*ExchangeOrderHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExchangeOrderHistoryCreate) createSpec() (*ExchangeOrderHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &ExchangeOrderHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exchangeorderhistory.Table, sqlgraph.NewFieldSpec(exchangeorderhistory.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ExchangeID(); ok {
		_spec.SetField(exchangeorderhistory.FieldExchangeID, field.TypeUUID, value)
		_node.ExchangeID = value
	}
	if value, ok := _c.mutation.Pair(); ok {
		_spec.SetField(exchangeorderhistory.FieldPair, field.TypeString, value)
		_node.Pair = value
	}
	if value, ok := _c.mutation.Side(); ok {
		_spec.SetField(exchangeorderhistory.FieldSide, field.TypeString, value)
		_node.Side = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(exchangeorderhistory.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(exchangeorderhistory.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(exchangeorderhistory.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(exchangeorderhistory.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.FilledQuantity(); ok {
		_spec.SetField(exchangeorderhistory.FieldFilledQuantity, field.TypeFloat64, value)
		_node.FilledQuantity = value
	}
	if value, ok := _c.mutation.ExchangeOrderID(); ok {
		_spec.SetField(exchangeorderhistory.FieldExchangeOrderID, field.TypeString, value)
		_node.ExchangeOrderID = value
	}
	if value, ok := _c.mutation.PlacedAt(); ok {
		_spec.SetField(exchangeorderhistory.FieldPlacedAt, field.TypeTime, value)
		_node.PlacedAt = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(exchangeorderhistory.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExchangeOrderHistory.Create().
//		SetExchangeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExchangeOrderHistoryUpsert) {
//			SetExchangeID(v+v).
//		}).
//		Exec(ctx)
func (_c *ExchangeOrderHistoryCreate) OnConflict(opts ...sql.ConflictOption) *ExchangeOrderHistoryUpsertOne {
	_c.conflict = opts
	return &ExchangeOrderHistoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExchangeOrderHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExchangeOrderHistoryCreate) OnConflictColumns(columns ...string) *ExchangeOrderHistoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExchangeOrderHistoryUpsertOne{
		create: _c,
	}
}

type (
	// ExchangeOrderHistoryUpsertOne is the builder for "upsert"-ing
	//  one ExchangeOrderHistory node.
	ExchangeOrderHistoryUpsertOne struct {
		create *ExchangeOrderHistoryCreate
	}

	// ExchangeOrderHistoryUpsert is the "OnConflict" setter.
	ExchangeOrderHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetExchangeID sets the "exchange_id" field.
func (u *ExchangeOrderHistoryUpsert) SetExchangeID(v uuid.UUID) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldExchangeID, v)
	return u
}

// UpdateExchangeID sets the "exchange_id" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdateExchangeID() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldExchangeID)
	return u
}

// SetPair sets the "pair" field.
func (u *ExchangeOrderHistoryUpsert) SetPair(v string) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldPair, v)
	return u
}

// UpdatePair sets the "pair" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdatePair() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldPair)
	return u
}

// SetSide sets the "side" field.
func (u *ExchangeOrderHistoryUpsert) SetSide(v string) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldSide, v)
	return u
}

// UpdateSide sets the "side" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdateSide() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldSide)
	return u
}

// SetType sets the "type" field.
func (u *ExchangeOrderHistoryUpsert) SetType(v string) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdateType() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldType)
	return u
}

// SetStatus sets the "status" field.
func (u *ExchangeOrderHistoryUpsert) SetStatus(v string) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdateStatus() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldStatus)
	return u
}

// SetPrice sets the "price" field.
func (u *ExchangeOrderHistoryUpsert) SetPrice(v float64) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdatePrice() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *ExchangeOrderHistoryUpsert) AddPrice(v float64) *ExchangeOrderHistoryUpsert {
	u.Add(exchangeorderhistory.FieldPrice, v)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *ExchangeOrderHistoryUpsert) SetQuantity(v float64) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdateQuantity() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *ExchangeOrderHistoryUpsert) AddQuantity(v float64) *ExchangeOrderHistoryUpsert {
	u.Add(exchangeorderhistory.FieldQuantity, v)
	return u
}

// SetFilledQuantity sets the "filled_quantity" field.
func (u *ExchangeOrderHistoryUpsert) SetFilledQuantity(v float64) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldFilledQuantity, v)
	return u
}

// UpdateFilledQuantity sets the "filled_quantity" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdateFilledQuantity() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldFilledQuantity)
	return u
}

// AddFilledQuantity adds v to the "filled_quantity" field.
func (u *ExchangeOrderHistoryUpsert) AddFilledQuantity(v float64) *ExchangeOrderHistoryUpsert {
	u.Add(exchangeorderhistory.FieldFilledQuantity, v)
	return u
}

// SetExchangeOrderID sets the "exchange_order_id" field.
func (u *ExchangeOrderHistoryUpsert) SetExchangeOrderID(v string) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldExchangeOrderID, v)
	return u
}

// UpdateExchangeOrderID sets the "exchange_order_id" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdateExchangeOrderID() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldExchangeOrderID)
	return u
}

// SetPlacedAt sets the "placed_at" field.
func (u *ExchangeOrderHistoryUpsert) SetPlacedAt(v time.Time) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldPlacedAt, v)
	return u
}

// UpdatePlacedAt sets the "placed_at" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdatePlacedAt() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldPlacedAt)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *ExchangeOrderHistoryUpsert) SetSyncedAt(v time.Time) *ExchangeOrderHistoryUpsert {
	u.Set(exchangeorderhistory.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsert) UpdateSyncedAt() *ExchangeOrderHistoryUpsert {
	u.SetExcluded(exchangeorderhistory.FieldSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ExchangeOrderHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exchangeorderhistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExchangeOrderHistoryUpsertOne) UpdateNewValues() *ExchangeOrderHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(exchangeorderhistory.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExchangeOrderHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExchangeOrderHistoryUpsertOne) Ignore() *ExchangeOrderHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExchangeOrderHistoryUpsertOne) DoNothing() *ExchangeOrderHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExchangeOrderHistoryCreate.OnConflict
// documentation for more info.
func (u *ExchangeOrderHistoryUpsertOne) Update(set func(*ExchangeOrderHistoryUpsert)) *ExchangeOrderHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExchangeOrderHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetExchangeID sets the "exchange_id" field.
func (u *ExchangeOrderHistoryUpsertOne) SetExchangeID(v uuid.UUID) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetExchangeID(v)
	})
}

// UpdateExchangeID sets the "exchange_id" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdateExchangeID() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateExchangeID()
	})
}

// SetPair sets the "pair" field.
func (u *ExchangeOrderHistoryUpsertOne) SetPair(v string) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetPair(v)
	})
}

// UpdatePair sets the "pair" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdatePair() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdatePair()
	})
}

// SetSide sets the "side" field.
func (u *ExchangeOrderHistoryUpsertOne) SetSide(v string) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetSide(v)
	})
}

// UpdateSide sets the "side" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdateSide() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateSide()
	})
}

// SetType sets the "type" field.
func (u *ExchangeOrderHistoryUpsertOne) SetType(v string) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdateType() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *ExchangeOrderHistoryUpsertOne) SetStatus(v string) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdateStatus() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateStatus()
	})
}

// SetPrice sets the "price" field.
func (u *ExchangeOrderHistoryUpsertOne) SetPrice(v float64) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ExchangeOrderHistoryUpsertOne) AddPrice(v float64) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdatePrice() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdatePrice()
	})
}

// SetQuantity sets the "quantity" field.
func (u *ExchangeOrderHistoryUpsertOne) SetQuantity(v float64) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *ExchangeOrderHistoryUpsertOne) AddQuantity(v float64) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdateQuantity() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateQuantity()
	})
}

// SetFilledQuantity sets the "filled_quantity" field.
func (u *ExchangeOrderHistoryUpsertOne) SetFilledQuantity(v float64) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetFilledQuantity(v)
	})
}

// AddFilledQuantity adds v to the "filled_quantity" field.
func (u *ExchangeOrderHistoryUpsertOne) AddFilledQuantity(v float64) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.AddFilledQuantity(v)
	})
}

// UpdateFilledQuantity sets the "filled_quantity" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdateFilledQuantity() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateFilledQuantity()
	})
}

// SetExchangeOrderID sets the "exchange_order_id" field.
func (u *ExchangeOrderHistoryUpsertOne) SetExchangeOrderID(v string) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetExchangeOrderID(v)
	})
}

// UpdateExchangeOrderID sets the "exchange_order_id" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdateExchangeOrderID() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateExchangeOrderID()
	})
}

// SetPlacedAt sets the "placed_at" field.
func (u *ExchangeOrderHistoryUpsertOne) SetPlacedAt(v time.Time) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetPlacedAt(v)
	})
}

// UpdatePlacedAt sets the "placed_at" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdatePlacedAt() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdatePlacedAt()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *ExchangeOrderHistoryUpsertOne) SetSyncedAt(v time.Time) *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertOne) UpdateSyncedAt() *ExchangeOrderHistoryUpsertOne {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *ExchangeOrderHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExchangeOrderHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExchangeOrderHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExchangeOrderHistoryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ExchangeOrderHistoryUpsertOne.ID is not supported by MySQL driver. Use ExchangeOrderHistoryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExchangeOrderHistoryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExchangeOrderHistoryCreateBulk is the builder for creating many ExchangeOrderHistory entities in bulk.
type ExchangeOrderHistoryCreateBulk struct {
	config
	err      error
	builders []*ExchangeOrderHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the ExchangeOrderHistory entities in the database.
func (_c *ExchangeOrderHistoryCreateBulk) Save(ctx context.Context) ([]*ExchangeOrderHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExchangeOrderHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExchangeOrderHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExchangeOrderHistoryCreateBulk) SaveX(ctx context.Context) []*ExchangeOrderHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeOrderHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeOrderHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExchangeOrderHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExchangeOrderHistoryUpsert) {
//			SetExchangeID(v+v).
//		}).
//		Exec(ctx)
func (_c *ExchangeOrderHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExchangeOrderHistoryUpsertBulk {
	_c.conflict = opts
	return &ExchangeOrderHistoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExchangeOrderHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExchangeOrderHistoryCreateBulk) OnConflictColumns(columns ...string) *ExchangeOrderHistoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExchangeOrderHistoryUpsertBulk{
		create: _c,
	}
}

// ExchangeOrderHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of ExchangeOrderHistory nodes.
type ExchangeOrderHistoryUpsertBulk struct {
	create *ExchangeOrderHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExchangeOrderHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exchangeorderhistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExchangeOrderHistoryUpsertBulk) UpdateNewValues() *ExchangeOrderHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(exchangeorderhistory.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExchangeOrderHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExchangeOrderHistoryUpsertBulk) Ignore() *ExchangeOrderHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExchangeOrderHistoryUpsertBulk) DoNothing() *ExchangeOrderHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExchangeOrderHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *ExchangeOrderHistoryUpsertBulk) Update(set func(*ExchangeOrderHistoryUpsert)) *ExchangeOrderHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExchangeOrderHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetExchangeID sets the "exchange_id" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetExchangeID(v uuid.UUID) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetExchangeID(v)
	})
}

// UpdateExchangeID sets the "exchange_id" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdateExchangeID() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateExchangeID()
	})
}

// SetPair sets the "pair" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetPair(v string) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetPair(v)
	})
}

// UpdatePair sets the "pair" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdatePair() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdatePair()
	})
}

// SetSide sets the "side" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetSide(v string) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetSide(v)
	})
}

// UpdateSide sets the "side" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdateSide() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateSide()
	})
}

// SetType sets the "type" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetType(v string) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdateType() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetStatus(v string) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdateStatus() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateStatus()
	})
}

// SetPrice sets the "price" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetPrice(v float64) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ExchangeOrderHistoryUpsertBulk) AddPrice(v float64) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdatePrice() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdatePrice()
	})
}

// SetQuantity sets the "quantity" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetQuantity(v float64) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *ExchangeOrderHistoryUpsertBulk) AddQuantity(v float64) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdateQuantity() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateQuantity()
	})
}

// SetFilledQuantity sets the "filled_quantity" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetFilledQuantity(v float64) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetFilledQuantity(v)
	})
}

// AddFilledQuantity adds v to the "filled_quantity" field.
func (u *ExchangeOrderHistoryUpsertBulk) AddFilledQuantity(v float64) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.AddFilledQuantity(v)
	})
}

// UpdateFilledQuantity sets the "filled_quantity" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdateFilledQuantity() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateFilledQuantity()
	})
}

// SetExchangeOrderID sets the "exchange_order_id" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetExchangeOrderID(v string) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetExchangeOrderID(v)
	})
}

// UpdateExchangeOrderID sets the "exchange_order_id" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdateExchangeOrderID() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateExchangeOrderID()
	})
}

// SetPlacedAt sets the "placed_at" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetPlacedAt(v time.Time) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetPlacedAt(v)
	})
}

// UpdatePlacedAt sets the "placed_at" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdatePlacedAt() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdatePlacedAt()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *ExchangeOrderHistoryUpsertBulk) SetSyncedAt(v time.Time) *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *ExchangeOrderHistoryUpsertBulk) UpdateSyncedAt() *ExchangeOrderHistoryUpsertBulk {
	return u.Update(func(s *ExchangeOrderHistoryUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *ExchangeOrderHistoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExchangeOrderHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExchangeOrderHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExchangeOrderHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
