// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"tradex/internal/infra/ent/exchange"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Exchange is the model entity for the Exchange schema.
type Exchange struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// APIKeyEncrypted holds the value of the "api_key_encrypted" field.
	APIKeyEncrypted string `json:"api_key_encrypted,omitempty"`
	// SecretKeyEncrypted holds the value of the "secret_key_encrypted" field.
	SecretKeyEncrypted string `json:"secret_key_encrypted,omitempty"`
	// PassphraseEncrypted holds the value of the "passphrase_encrypted" field.
	PassphraseEncrypted *string `json:"passphrase_encrypted,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastTestedAt holds the value of the "last_tested_at" field.
	LastTestedAt *time.Time `json:"last_tested_at,omitempty"`
	// TestResult holds the value of the "test_result" field.
	TestResult *string `json:"test_result,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Exchange) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exchange.FieldName, exchange.FieldType, exchange.FieldAPIKeyEncrypted, exchange.FieldSecretKeyEncrypted, exchange.FieldPassphraseEncrypted, exchange.FieldStatus, exchange.FieldTestResult:
			values[i] = new(sql.NullString)
		case exchange.FieldLastTestedAt, exchange.FieldCreatedAt, exchange.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case exchange.FieldID, exchange.FieldCreatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Exchange fields.
func (_m *Exchange) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exchange.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case exchange.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case exchange.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case exchange.FieldAPIKeyEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_encrypted", values[i])
			} else if value.Valid {
				_m.APIKeyEncrypted = value.String
			}
		case exchange.FieldSecretKeyEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_key_encrypted", values[i])
			} else if value.Valid {
				_m.SecretKeyEncrypted = value.String
			}
		case exchange.FieldPassphraseEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field passphrase_encrypted", values[i])
			} else if value.Valid {
				_m.PassphraseEncrypted = new(string)
				*_m.PassphraseEncrypted = value.String
			}
		case exchange.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case exchange.FieldLastTestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_tested_at", values[i])
			} else if value.Valid {
				_m.LastTestedAt = new(time.Time)
				*_m.LastTestedAt = value.Time
			}
		case exchange.FieldTestResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field test_result", values[i])
			} else if value.Valid {
				_m.TestResult = new(string)
				*_m.TestResult = value.String
			}
		case exchange.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case exchange.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case exchange.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Exchange.
// This includes values selected through modifiers, order, etc.
func (_m *Exchange) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Exchange.
// Note that you need to call Exchange.Unwrap() before calling this method if this Exchange
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Exchange) Update() *ExchangeUpdateOne {
	return NewExchangeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Exchange entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Exchange) Unwrap() *Exchange {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Exchange is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Exchange) String() string {
	var builder strings.Builder
	builder.WriteString("Exchange(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("api_key_encrypted=")
	builder.WriteString(_m.APIKeyEncrypted)
	builder.WriteString(", ")
	builder.WriteString("secret_key_encrypted=")
	builder.WriteString(_m.SecretKeyEncrypted)
	builder.WriteString(", ")
	if v := _m.PassphraseEncrypted; v != nil {
		builder.WriteString("passphrase_encrypted=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastTestedAt; v != nil {
		builder.WriteString("last_tested_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TestResult; v != nil {
		builder.WriteString("test_result=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Exchanges is a parsable slice of Exchange.
type Exchanges []*Exchange
