// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tradex/internal/infra/ent/exchange"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ExchangeCreate is the builder for creating a Exchange entity.
type ExchangeCreate struct {
	config
	mutation *ExchangeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ExchangeCreate) SetName(v string) *ExchangeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableName(v *string) *ExchangeCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ExchangeCreate) SetType(v string) *ExchangeCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableType(v *string) *ExchangeCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_c *ExchangeCreate) SetAPIKeyEncrypted(v string) *ExchangeCreate {
	_c.mutation.SetAPIKeyEncrypted(v)
	return _c
}

// SetNillableAPIKeyEncrypted sets the "api_key_encrypted" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableAPIKeyEncrypted(v *string) *ExchangeCreate {
	if v != nil {
		_c.SetAPIKeyEncrypted(*v)
	}
	return _c
}

// SetSecretKeyEncrypted sets the "secret_key_encrypted" field.
func (_c *ExchangeCreate) SetSecretKeyEncrypted(v string) *ExchangeCreate {
	_c.mutation.SetSecretKeyEncrypted(v)
	return _c
}

// SetNillableSecretKeyEncrypted sets the "secret_key_encrypted" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableSecretKeyEncrypted(v *string) *ExchangeCreate {
	if v != nil {
		_c.SetSecretKeyEncrypted(*v)
	}
	return _c
}

// SetPassphraseEncrypted sets the "passphrase_encrypted" field.
func (_c *ExchangeCreate) SetPassphraseEncrypted(v string) *ExchangeCreate {
	_c.mutation.SetPassphraseEncrypted(v)
	return _c
}

// SetNillablePassphraseEncrypted sets the "passphrase_encrypted" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillablePassphraseEncrypted(v *string) *ExchangeCreate {
	if v != nil {
		_c.SetPassphraseEncrypted(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExchangeCreate) SetStatus(v string) *ExchangeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableStatus(v *string) *ExchangeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastTestedAt sets the "last_tested_at" field.
func (_c *ExchangeCreate) SetLastTestedAt(v time.Time) *ExchangeCreate {
	_c.mutation.SetLastTestedAt(v)
	return _c
}

// SetNillableLastTestedAt sets the "last_tested_at" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableLastTestedAt(v *time.Time) *ExchangeCreate {
	if v != nil {
		_c.SetLastTestedAt(*v)
	}
	return _c
}

// SetTestResult sets the "test_result" field.
func (_c *ExchangeCreate) SetTestResult(v string) *ExchangeCreate {
	_c.mutation.SetTestResult(v)
	return _c
}

// SetNillableTestResult sets the "test_result" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableTestResult(v *string) *ExchangeCreate {
	if v != nil {
		_c.SetTestResult(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ExchangeCreate) SetCreatedBy(v uuid.UUID) *ExchangeCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableCreatedBy(v *uuid.UUID) *ExchangeCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExchangeCreate) SetCreatedAt(v time.Time) *ExchangeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableCreatedAt(v *time.Time) *ExchangeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExchangeCreate) SetUpdatedAt(v time.Time) *ExchangeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableUpdatedAt(v *time.Time) *ExchangeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExchangeCreate) SetID(v uuid.UUID) *ExchangeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExchangeCreate) SetNillableID(v *uuid.UUID) *ExchangeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ExchangeMutation object of the builder.
func (_c *ExchangeCreate) Mutation() *ExchangeMutation {
	return _c.mutation
}

// Save creates the Exchange in the database.
func (_c *ExchangeCreate) Save(ctx context.Context) (*Exchange, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExchangeCreate) SaveX(ctx context.Context) *Exchange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExchangeCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := exchange.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := exchange.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.APIKeyEncrypted(); !ok {
		v := exchange.DefaultAPIKeyEncrypted
		_c.mutation.SetAPIKeyEncrypted(v)
	}
	if _, ok := _c.mutation.SecretKeyEncrypted(); !ok {
		v := exchange.DefaultSecretKeyEncrypted
		_c.mutation.SetSecretKeyEncrypted(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := exchange.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := exchange.DefaultCreatedBy()
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := exchange.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := exchange.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := exchange.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExchangeCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Exchange.name"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Exchange.type"`)}
	}
	if _, ok := _c.mutation.APIKeyEncrypted(); !ok {
		return &ValidationError{Name: "api_key_encrypted", err: errors.New(`ent: missing required field "Exchange.api_key_encrypted"`)}
	}
	if _, ok := _c.mutation.SecretKeyEncrypted(); !ok {
		return &ValidationError{Name: "secret_key_encrypted", err: errors.New(`ent: missing required field "Exchange.secret_key_encrypted"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Exchange.status"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Exchange.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Exchange.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Exchange.updated_at"`)}
	}
	return nil
}

func (_c *ExchangeCreate) sqlSave(ctx context.Context) (*Exchange, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExchangeCreate) createSpec() (*Exchange, *sqlgraph.CreateSpec) {
	var (
		_node = &Exchange{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exchange.Table, sqlgraph.NewFieldSpec(exchange.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(exchange.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(exchange.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(exchange.FieldAPIKeyEncrypted, field.TypeString, value)
		_node.APIKeyEncrypted = value
	}
	if value, ok := _c.mutation.SecretKeyEncrypted(); ok {
		_spec.SetField(exchange.FieldSecretKeyEncrypted, field.TypeString, value)
		_node.SecretKeyEncrypted = value
	}
	if value, ok := _c.mutation.PassphraseEncrypted(); ok {
		_spec.SetField(exchange.FieldPassphraseEncrypted, field.TypeString, value)
		_node.PassphraseEncrypted = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(exchange.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastTestedAt(); ok {
		_spec.SetField(exchange.FieldLastTestedAt, field.TypeTime, value)
		_node.LastTestedAt = &value
	}
	if value, ok := _c.mutation.TestResult(); ok {
		_spec.SetField(exchange.FieldTestResult, field.TypeString, value)
		_node.TestResult = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(exchange.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(exchange.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(exchange.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Exchange.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExchangeUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ExchangeCreate) OnConflict(opts ...sql.ConflictOption) *ExchangeUpsertOne {
	_c.conflict = opts
	return &ExchangeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Exchange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExchangeCreate) OnConflictColumns(columns ...string) *ExchangeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExchangeUpsertOne{
		create: _c,
	}
}

type (
	// ExchangeUpsertOne is the builder for "upsert"-ing
	//  one Exchange node.
	ExchangeUpsertOne struct {
		create *ExchangeCreate
	}

	// ExchangeUpsert is the "OnConflict" setter.
	ExchangeUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ExchangeUpsert) SetName(v string) *ExchangeUpsert {
	u.Set(exchange.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdateName() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *ExchangeUpsert) SetType(v string) *ExchangeUpsert {
	u.Set(exchange.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdateType() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldType)
	return u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (u *ExchangeUpsert) SetAPIKeyEncrypted(v string) *ExchangeUpsert {
	u.Set(exchange.FieldAPIKeyEncrypted, v)
	return u
}

// UpdateAPIKeyEncrypted sets the "api_key_encrypted" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdateAPIKeyEncrypted() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldAPIKeyEncrypted)
	return u
}

// SetSecretKeyEncrypted sets the "secret_key_encrypted" field.
func (u *ExchangeUpsert) SetSecretKeyEncrypted(v string) *ExchangeUpsert {
	u.Set(exchange.FieldSecretKeyEncrypted, v)
	return u
}

// UpdateSecretKeyEncrypted sets the "secret_key_encrypted" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdateSecretKeyEncrypted() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldSecretKeyEncrypted)
	return u
}

// SetPassphraseEncrypted sets the "passphrase_encrypted" field.
func (u *ExchangeUpsert) SetPassphraseEncrypted(v string) *ExchangeUpsert {
	u.Set(exchange.FieldPassphraseEncrypted, v)
	return u
}

// UpdatePassphraseEncrypted sets the "passphrase_encrypted" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdatePassphraseEncrypted() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldPassphraseEncrypted)
	return u
}

// ClearPassphraseEncrypted clears the value of the "passphrase_encrypted" field.
func (u *ExchangeUpsert) ClearPassphraseEncrypted() *ExchangeUpsert {
	u.SetNull(exchange.FieldPassphraseEncrypted)
	return u
}

// SetStatus sets the "status" field.
func (u *ExchangeUpsert) SetStatus(v string) *ExchangeUpsert {
	u.Set(exchange.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdateStatus() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldStatus)
	return u
}

// SetLastTestedAt sets the "last_tested_at" field.
func (u *ExchangeUpsert) SetLastTestedAt(v time.Time) *ExchangeUpsert {
	u.Set(exchange.FieldLastTestedAt, v)
	return u
}

// UpdateLastTestedAt sets the "last_tested_at" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdateLastTestedAt() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldLastTestedAt)
	return u
}

// ClearLastTestedAt clears the value of the "last_tested_at" field.
func (u *ExchangeUpsert) ClearLastTestedAt() *ExchangeUpsert {
	u.SetNull(exchange.FieldLastTestedAt)
	return u
}

// SetTestResult sets the "test_result" field.
func (u *ExchangeUpsert) SetTestResult(v string) *ExchangeUpsert {
	u.Set(exchange.FieldTestResult, v)
	return u
}

// UpdateTestResult sets the "test_result" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdateTestResult() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldTestResult)
	return u
}

// ClearTestResult clears the value of the "test_result" field.
func (u *ExchangeUpsert) ClearTestResult() *ExchangeUpsert {
	u.SetNull(exchange.FieldTestResult)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ExchangeUpsert) SetCreatedBy(v uuid.UUID) *ExchangeUpsert {
	u.Set(exchange.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdateCreatedBy() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldCreatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExchangeUpsert) SetUpdatedAt(v time.Time) *ExchangeUpsert {
	u.Set(exchange.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExchangeUpsert) UpdateUpdatedAt() *ExchangeUpsert {
	u.SetExcluded(exchange.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Exchange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exchange.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExchangeUpsertOne) UpdateNewValues() *ExchangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(exchange.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(exchange.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Exchange.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExchangeUpsertOne) Ignore() *ExchangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExchangeUpsertOne) DoNothing() *ExchangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExchangeCreate.OnConflict
// documentation for more info.
func (u *ExchangeUpsertOne) Update(set func(*ExchangeUpsert)) *ExchangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExchangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ExchangeUpsertOne) SetName(v string) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdateName() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *ExchangeUpsertOne) SetType(v string) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdateType() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateType()
	})
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (u *ExchangeUpsertOne) SetAPIKeyEncrypted(v string) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetAPIKeyEncrypted(v)
	})
}

// UpdateAPIKeyEncrypted sets the "api_key_encrypted" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdateAPIKeyEncrypted() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateAPIKeyEncrypted()
	})
}

// SetSecretKeyEncrypted sets the "secret_key_encrypted" field.
func (u *ExchangeUpsertOne) SetSecretKeyEncrypted(v string) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetSecretKeyEncrypted(v)
	})
}

// UpdateSecretKeyEncrypted sets the "secret_key_encrypted" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdateSecretKeyEncrypted() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateSecretKeyEncrypted()
	})
}

// SetPassphraseEncrypted sets the "passphrase_encrypted" field.
func (u *ExchangeUpsertOne) SetPassphraseEncrypted(v string) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetPassphraseEncrypted(v)
	})
}

// UpdatePassphraseEncrypted sets the "passphrase_encrypted" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdatePassphraseEncrypted() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdatePassphraseEncrypted()
	})
}

// ClearPassphraseEncrypted clears the value of the "passphrase_encrypted" field.
func (u *ExchangeUpsertOne) ClearPassphraseEncrypted() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.ClearPassphraseEncrypted()
	})
}

// SetStatus sets the "status" field.
func (u *ExchangeUpsertOne) SetStatus(v string) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdateStatus() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateStatus()
	})
}

// SetLastTestedAt sets the "last_tested_at" field.
func (u *ExchangeUpsertOne) SetLastTestedAt(v time.Time) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetLastTestedAt(v)
	})
}

// UpdateLastTestedAt sets the "last_tested_at" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdateLastTestedAt() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateLastTestedAt()
	})
}

// ClearLastTestedAt clears the value of the "last_tested_at" field.
func (u *ExchangeUpsertOne) ClearLastTestedAt() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.ClearLastTestedAt()
	})
}

// SetTestResult sets the "test_result" field.
func (u *ExchangeUpsertOne) SetTestResult(v string) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetTestResult(v)
	})
}

// UpdateTestResult sets the "test_result" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdateTestResult() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateTestResult()
	})
}

// ClearTestResult clears the value of the "test_result" field.
func (u *ExchangeUpsertOne) ClearTestResult() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.ClearTestResult()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExchangeUpsertOne) SetCreatedBy(v uuid.UUID) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdateCreatedBy() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExchangeUpsertOne) SetUpdatedAt(v time.Time) *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExchangeUpsertOne) UpdateUpdatedAt() *ExchangeUpsertOne {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExchangeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExchangeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExchangeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExchangeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ExchangeUpsertOne.ID is not supported by MySQL driver. Use ExchangeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExchangeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExchangeCreateBulk is the builder for creating many Exchange entities in bulk.
type ExchangeCreateBulk struct {
	config
	err      error
	builders []*ExchangeCreate
	conflict []sql.ConflictOption
}

// Save creates the Exchange entities in the database.
func (_c *ExchangeCreateBulk) Save(ctx context.Context) ([]*Exchange, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Exchange, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExchangeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExchangeCreateBulk) SaveX(ctx context.Context) []*Exchange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Exchange.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExchangeUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ExchangeCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExchangeUpsertBulk {
	_c.conflict = opts
	return &ExchangeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Exchange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExchangeCreateBulk) OnConflictColumns(columns ...string) *ExchangeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExchangeUpsertBulk{
		create: _c,
	}
}

// ExchangeUpsertBulk is the builder for "upsert"-ing
// a bulk of Exchange nodes.
type ExchangeUpsertBulk struct {
	create *ExchangeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Exchange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exchange.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExchangeUpsertBulk) UpdateNewValues() *ExchangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(exchange.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(exchange.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Exchange.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExchangeUpsertBulk) Ignore() *ExchangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExchangeUpsertBulk) DoNothing() *ExchangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExchangeCreateBulk.OnConflict
// documentation for more info.
func (u *ExchangeUpsertBulk) Update(set func(*ExchangeUpsert)) *ExchangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExchangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ExchangeUpsertBulk) SetName(v string) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdateName() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *ExchangeUpsertBulk) SetType(v string) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdateType() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateType()
	})
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (u *ExchangeUpsertBulk) SetAPIKeyEncrypted(v string) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetAPIKeyEncrypted(v)
	})
}

// UpdateAPIKeyEncrypted sets the "api_key_encrypted" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdateAPIKeyEncrypted() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateAPIKeyEncrypted()
	})
}

// SetSecretKeyEncrypted sets the "secret_key_encrypted" field.
func (u *ExchangeUpsertBulk) SetSecretKeyEncrypted(v string) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetSecretKeyEncrypted(v)
	})
}

// UpdateSecretKeyEncrypted sets the "secret_key_encrypted" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdateSecretKeyEncrypted() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateSecretKeyEncrypted()
	})
}

// SetPassphraseEncrypted sets the "passphrase_encrypted" field.
func (u *ExchangeUpsertBulk) SetPassphraseEncrypted(v string) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetPassphraseEncrypted(v)
	})
}

// UpdatePassphraseEncrypted sets the "passphrase_encrypted" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdatePassphraseEncrypted() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdatePassphraseEncrypted()
	})
}

// ClearPassphraseEncrypted clears the value of the "passphrase_encrypted" field.
func (u *ExchangeUpsertBulk) ClearPassphraseEncrypted() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.ClearPassphraseEncrypted()
	})
}

// SetStatus sets the "status" field.
func (u *ExchangeUpsertBulk) SetStatus(v string) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdateStatus() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateStatus()
	})
}

// SetLastTestedAt sets the "last_tested_at" field.
func (u *ExchangeUpsertBulk) SetLastTestedAt(v time.Time) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetLastTestedAt(v)
	})
}

// UpdateLastTestedAt sets the "last_tested_at" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdateLastTestedAt() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateLastTestedAt()
	})
}

// ClearLastTestedAt clears the value of the "last_tested_at" field.
func (u *ExchangeUpsertBulk) ClearLastTestedAt() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.ClearLastTestedAt()
	})
}

// SetTestResult sets the "test_result" field.
func (u *ExchangeUpsertBulk) SetTestResult(v string) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetTestResult(v)
	})
}

// UpdateTestResult sets the "test_result" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdateTestResult() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateTestResult()
	})
}

// ClearTestResult clears the value of the "test_result" field.
func (u *ExchangeUpsertBulk) ClearTestResult() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.ClearTestResult()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExchangeUpsertBulk) SetCreatedBy(v uuid.UUID) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdateCreatedBy() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExchangeUpsertBulk) SetUpdatedAt(v time.Time) *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExchangeUpsertBulk) UpdateUpdatedAt() *ExchangeUpsertBulk {
	return u.Update(func(s *ExchangeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExchangeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExchangeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExchangeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExchangeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
