// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tradex/internal/infra/ent/order"
	"tradex/internal/infra/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTraderID sets the "trader_id" field.
func (_u *OrderUpdate) SetTraderID(v uuid.UUID) *OrderUpdate {
	_u.mutation.SetTraderID(v)
	return _u
}

// SetNillableTraderID sets the "trader_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableTraderID(v *uuid.UUID) *OrderUpdate {
	if v != nil {
		_u.SetTraderID(*v)
	}
	return _u
}

// SetClientOrderID sets the "client_order_id" field.
func (_u *OrderUpdate) SetClientOrderID(v uuid.UUID) *OrderUpdate {
	_u.mutation.SetClientOrderID(v)
	return _u
}

// SetNillableClientOrderID sets the "client_order_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableClientOrderID(v *uuid.UUID) *OrderUpdate {
	if v != nil {
		_u.SetClientOrderID(*v)
	}
	return _u
}

// SetExchangeOrderID sets the "exchange_order_id" field.
func (_u *OrderUpdate) SetExchangeOrderID(v string) *OrderUpdate {
	_u.mutation.SetExchangeOrderID(v)
	return _u
}

// SetNillableExchangeOrderID sets the "exchange_order_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableExchangeOrderID(v *string) *OrderUpdate {
	if v != nil {
		_u.SetExchangeOrderID(*v)
	}
	return _u
}

// ClearExchangeOrderID clears the value of the "exchange_order_id" field.
func (_u *OrderUpdate) ClearExchangeOrderID() *OrderUpdate {
	_u.mutation.ClearExchangeOrderID()
	return _u
}

// SetExchangeID sets the "exchange_id" field.
func (_u *OrderUpdate) SetExchangeID(v uuid.UUID) *OrderUpdate {
	_u.mutation.SetExchangeID(v)
	return _u
}

// SetNillableExchangeID sets the "exchange_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableExchangeID(v *uuid.UUID) *OrderUpdate {
	if v != nil {
		_u.SetExchangeID(*v)
	}
	return _u
}

// SetStrategyID sets the "strategy_id" field.
func (_u *OrderUpdate) SetStrategyID(v uuid.UUID) *OrderUpdate {
	_u.mutation.SetStrategyID(v)
	return _u
}

// SetNillableStrategyID sets the "strategy_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStrategyID(v *uuid.UUID) *OrderUpdate {
	if v != nil {
		_u.SetStrategyID(*v)
	}
	return _u
}

// ClearStrategyID clears the value of the "strategy_id" field.
func (_u *OrderUpdate) ClearStrategyID() *OrderUpdate {
	_u.mutation.ClearStrategyID()
	return _u
}

// SetPositionID sets the "position_id" field.
func (_u *OrderUpdate) SetPositionID(v uuid.UUID) *OrderUpdate {
	_u.mutation.SetPositionID(v)
	return _u
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePositionID(v *uuid.UUID) *OrderUpdate {
	if v != nil {
		_u.SetPositionID(*v)
	}
	return _u
}

// ClearPositionID clears the value of the "position_id" field.
func (_u *OrderUpdate) ClearPositionID() *OrderUpdate {
	_u.mutation.ClearPositionID()
	return _u
}

// SetPair sets the "pair" field.
func (_u *OrderUpdate) SetPair(v string) *OrderUpdate {
	_u.mutation.SetPair(v)
	return _u
}

// SetNillablePair sets the "pair" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePair(v *string) *OrderUpdate {
	if v != nil {
		_u.SetPair(*v)
	}
	return _u
}

// SetSide sets the "side" field.
func (_u *OrderUpdate) SetSide(v string) *OrderUpdate {
	_u.mutation.SetSide(v)
	return _u
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableSide(v *string) *OrderUpdate {
	if v != nil {
		_u.SetSide(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *OrderUpdate) SetType(v string) *OrderUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableType(v *string) *OrderUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v string) *OrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *string) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *OrderUpdate) SetPrice(v float64) *OrderUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePrice(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *OrderUpdate) AddPrice(v float64) *OrderUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *OrderUpdate) ClearPrice() *OrderUpdate {
	_u.mutation.ClearPrice()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderUpdate) SetQuantity(v float64) *OrderUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableQuantity(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderUpdate) AddQuantity(v float64) *OrderUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetFilledQuantity sets the "filled_quantity" field.
func (_u *OrderUpdate) SetFilledQuantity(v float64) *OrderUpdate {
	_u.mutation.ResetFilledQuantity()
	_u.mutation.SetFilledQuantity(v)
	return _u
}

// SetNillableFilledQuantity sets the "filled_quantity" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableFilledQuantity(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetFilledQuantity(*v)
	}
	return _u
}

// AddFilledQuantity adds value to the "filled_quantity" field.
func (_u *OrderUpdate) AddFilledQuantity(v float64) *OrderUpdate {
	_u.mutation.AddFilledQuantity(v)
	return _u
}

// SetQuoteQuantity sets the "quote_quantity" field.
func (_u *OrderUpdate) SetQuoteQuantity(v float64) *OrderUpdate {
	_u.mutation.ResetQuoteQuantity()
	_u.mutation.SetQuoteQuantity(v)
	return _u
}

// SetNillableQuoteQuantity sets the "quote_quantity" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableQuoteQuantity(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetQuoteQuantity(*v)
	}
	return _u
}

// AddQuoteQuantity adds value to the "quote_quantity" field.
func (_u *OrderUpdate) AddQuoteQuantity(v float64) *OrderUpdate {
	_u.mutation.AddQuoteQuantity(v)
	return _u
}

// SetFee sets the "fee" field.
func (_u *OrderUpdate) SetFee(v float64) *OrderUpdate {
	_u.mutation.ResetFee()
	_u.mutation.SetFee(v)
	return _u
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableFee(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetFee(*v)
	}
	return _u
}

// AddFee adds value to the "fee" field.
func (_u *OrderUpdate) AddFee(v float64) *OrderUpdate {
	_u.mutation.AddFee(v)
	return _u
}

// SetFeeAsset sets the "fee_asset" field.
func (_u *OrderUpdate) SetFeeAsset(v string) *OrderUpdate {
	_u.mutation.SetFeeAsset(v)
	return _u
}

// SetNillableFeeAsset sets the "fee_asset" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableFeeAsset(v *string) *OrderUpdate {
	if v != nil {
		_u.SetFeeAsset(*v)
	}
	return _u
}

// ClearFeeAsset clears the value of the "fee_asset" field.
func (_u *OrderUpdate) ClearFeeAsset() *OrderUpdate {
	_u.mutation.ClearFeeAsset()
	return _u
}

// SetIsManual sets the "is_manual" field.
func (_u *OrderUpdate) SetIsManual(v bool) *OrderUpdate {
	_u.mutation.SetIsManual(v)
	return _u
}

// SetNillableIsManual sets the "is_manual" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableIsManual(v *bool) *OrderUpdate {
	if v != nil {
		_u.SetIsManual(*v)
	}
	return _u
}

// SetPlacedAtUtc sets the "placed_at_utc" field.
func (_u *OrderUpdate) SetPlacedAtUtc(v time.Time) *OrderUpdate {
	_u.mutation.SetPlacedAtUtc(v)
	return _u
}

// SetNillablePlacedAtUtc sets the "placed_at_utc" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePlacedAtUtc(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetPlacedAtUtc(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdate) SetUpdatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableUpdatedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *OrderUpdate) SetVersion(v uuid.UUID) *OrderUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableVersion(v *uuid.UUID) *OrderUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TraderID(); ok {
		_spec.SetField(order.FieldTraderID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ClientOrderID(); ok {
		_spec.SetField(order.FieldClientOrderID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExchangeOrderID(); ok {
		_spec.SetField(order.FieldExchangeOrderID, field.TypeString, value)
	}
	if _u.mutation.ExchangeOrderIDCleared() {
		_spec.ClearField(order.FieldExchangeOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.ExchangeID(); ok {
		_spec.SetField(order.FieldExchangeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StrategyID(); ok {
		_spec.SetField(order.FieldStrategyID, field.TypeUUID, value)
	}
	if _u.mutation.StrategyIDCleared() {
		_spec.ClearField(order.FieldStrategyID, field.TypeUUID)
	}
	if value, ok := _u.mutation.PositionID(); ok {
		_spec.SetField(order.FieldPositionID, field.TypeUUID, value)
	}
	if _u.mutation.PositionIDCleared() {
		_spec.ClearField(order.FieldPositionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Pair(); ok {
		_spec.SetField(order.FieldPair, field.TypeString, value)
	}
	if value, ok := _u.mutation.Side(); ok {
		_spec.SetField(order.FieldSide, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(order.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(order.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(order.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(order.FieldPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(order.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FilledQuantity(); ok {
		_spec.SetField(order.FieldFilledQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFilledQuantity(); ok {
		_spec.AddField(order.FieldFilledQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuoteQuantity(); ok {
		_spec.SetField(order.FieldQuoteQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuoteQuantity(); ok {
		_spec.AddField(order.FieldQuoteQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fee(); ok {
		_spec.SetField(order.FieldFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFee(); ok {
		_spec.AddField(order.FieldFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeAsset(); ok {
		_spec.SetField(order.FieldFeeAsset, field.TypeString, value)
	}
	if _u.mutation.FeeAssetCleared() {
		_spec.ClearField(order.FieldFeeAsset, field.TypeString)
	}
	if value, ok := _u.mutation.IsManual(); ok {
		_spec.SetField(order.FieldIsManual, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PlacedAtUtc(); ok {
		_spec.SetField(order.FieldPlacedAtUtc, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(order.FieldVersion, field.TypeUUID, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetTraderID sets the "trader_id" field.
func (_u *OrderUpdateOne) SetTraderID(v uuid.UUID) *OrderUpdateOne {
	_u.mutation.SetTraderID(v)
	return _u
}

// SetNillableTraderID sets the "trader_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTraderID(v *uuid.UUID) *OrderUpdateOne {
	if v != nil {
		_u.SetTraderID(*v)
	}
	return _u
}

// SetClientOrderID sets the "client_order_id" field.
func (_u *OrderUpdateOne) SetClientOrderID(v uuid.UUID) *OrderUpdateOne {
	_u.mutation.SetClientOrderID(v)
	return _u
}

// SetNillableClientOrderID sets the "client_order_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableClientOrderID(v *uuid.UUID) *OrderUpdateOne {
	if v != nil {
		_u.SetClientOrderID(*v)
	}
	return _u
}

// SetExchangeOrderID sets the "exchange_order_id" field.
func (_u *OrderUpdateOne) SetExchangeOrderID(v string) *OrderUpdateOne {
	_u.mutation.SetExchangeOrderID(v)
	return _u
}

// SetNillableExchangeOrderID sets the "exchange_order_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableExchangeOrderID(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetExchangeOrderID(*v)
	}
	return _u
}

// ClearExchangeOrderID clears the value of the "exchange_order_id" field.
func (_u *OrderUpdateOne) ClearExchangeOrderID() *OrderUpdateOne {
	_u.mutation.ClearExchangeOrderID()
	return _u
}

// SetExchangeID sets the "exchange_id" field.
func (_u *OrderUpdateOne) SetExchangeID(v uuid.UUID) *OrderUpdateOne {
	_u.mutation.SetExchangeID(v)
	return _u
}

// SetNillableExchangeID sets the "exchange_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableExchangeID(v *uuid.UUID) *OrderUpdateOne {
	if v != nil {
		_u.SetExchangeID(*v)
	}
	return _u
}

// SetStrategyID sets the "strategy_id" field.
func (_u *OrderUpdateOne) SetStrategyID(v uuid.UUID) *OrderUpdateOne {
	_u.mutation.SetStrategyID(v)
	return _u
}

// SetNillableStrategyID sets the "strategy_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStrategyID(v *uuid.UUID) *OrderUpdateOne {
	if v != nil {
		_u.SetStrategyID(*v)
	}
	return _u
}

// ClearStrategyID clears the value of the "strategy_id" field.
func (_u *OrderUpdateOne) ClearStrategyID() *OrderUpdateOne {
	_u.mutation.ClearStrategyID()
	return _u
}

// SetPositionID sets the "position_id" field.
func (_u *OrderUpdateOne) SetPositionID(v uuid.UUID) *OrderUpdateOne {
	_u.mutation.SetPositionID(v)
	return _u
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePositionID(v *uuid.UUID) *OrderUpdateOne {
	if v != nil {
		_u.SetPositionID(*v)
	}
	return _u
}

// ClearPositionID clears the value of the "position_id" field.
func (_u *OrderUpdateOne) ClearPositionID() *OrderUpdateOne {
	_u.mutation.ClearPositionID()
	return _u
}

// SetPair sets the "pair" field.
func (_u *OrderUpdateOne) SetPair(v string) *OrderUpdateOne {
	_u.mutation.SetPair(v)
	return _u
}

// SetNillablePair sets the "pair" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePair(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetPair(*v)
	}
	return _u
}

// SetSide sets the "side" field.
func (_u *OrderUpdateOne) SetSide(v string) *OrderUpdateOne {
	_u.mutation.SetSide(v)
	return _u
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableSide(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetSide(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *OrderUpdateOne) SetType(v string) *OrderUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableType(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v string) *OrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *OrderUpdateOne) SetPrice(v float64) *OrderUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePrice(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *OrderUpdateOne) AddPrice(v float64) *OrderUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *OrderUpdateOne) ClearPrice() *OrderUpdateOne {
	_u.mutation.ClearPrice()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderUpdateOne) SetQuantity(v float64) *OrderUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableQuantity(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderUpdateOne) AddQuantity(v float64) *OrderUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetFilledQuantity sets the "filled_quantity" field.
func (_u *OrderUpdateOne) SetFilledQuantity(v float64) *OrderUpdateOne {
	_u.mutation.ResetFilledQuantity()
	_u.mutation.SetFilledQuantity(v)
	return _u
}

// SetNillableFilledQuantity sets the "filled_quantity" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableFilledQuantity(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetFilledQuantity(*v)
	}
	return _u
}

// AddFilledQuantity adds value to the "filled_quantity" field.
func (_u *OrderUpdateOne) AddFilledQuantity(v float64) *OrderUpdateOne {
	_u.mutation.AddFilledQuantity(v)
	return _u
}

// SetQuoteQuantity sets the "quote_quantity" field.
func (_u *OrderUpdateOne) SetQuoteQuantity(v float64) *OrderUpdateOne {
	_u.mutation.ResetQuoteQuantity()
	_u.mutation.SetQuoteQuantity(v)
	return _u
}

// SetNillableQuoteQuantity sets the "quote_quantity" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableQuoteQuantity(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetQuoteQuantity(*v)
	}
	return _u
}

// AddQuoteQuantity adds value to the "quote_quantity" field.
func (_u *OrderUpdateOne) AddQuoteQuantity(v float64) *OrderUpdateOne {
	_u.mutation.AddQuoteQuantity(v)
	return _u
}

// SetFee sets the "fee" field.
func (_u *OrderUpdateOne) SetFee(v float64) *OrderUpdateOne {
	_u.mutation.ResetFee()
	_u.mutation.SetFee(v)
	return _u
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableFee(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetFee(*v)
	}
	return _u
}

// AddFee adds value to the "fee" field.
func (_u *OrderUpdateOne) AddFee(v float64) *OrderUpdateOne {
	_u.mutation.AddFee(v)
	return _u
}

// SetFeeAsset sets the "fee_asset" field.
func (_u *OrderUpdateOne) SetFeeAsset(v string) *OrderUpdateOne {
	_u.mutation.SetFeeAsset(v)
	return _u
}

// SetNillableFeeAsset sets the "fee_asset" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableFeeAsset(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetFeeAsset(*v)
	}
	return _u
}

// ClearFeeAsset clears the value of the "fee_asset" field.
func (_u *OrderUpdateOne) ClearFeeAsset() *OrderUpdateOne {
	_u.mutation.ClearFeeAsset()
	return _u
}

// SetIsManual sets the "is_manual" field.
func (_u *OrderUpdateOne) SetIsManual(v bool) *OrderUpdateOne {
	_u.mutation.SetIsManual(v)
	return _u
}

// SetNillableIsManual sets the "is_manual" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableIsManual(v *bool) *OrderUpdateOne {
	if v != nil {
		_u.SetIsManual(*v)
	}
	return _u
}

// SetPlacedAtUtc sets the "placed_at_utc" field.
func (_u *OrderUpdateOne) SetPlacedAtUtc(v time.Time) *OrderUpdateOne {
	_u.mutation.SetPlacedAtUtc(v)
	return _u
}

// SetNillablePlacedAtUtc sets the "placed_at_utc" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePlacedAtUtc(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetPlacedAtUtc(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdateOne) SetUpdatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableUpdatedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *OrderUpdateOne) SetVersion(v uuid.UUID) *OrderUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableVersion(v *uuid.UUID) *OrderUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TraderID(); ok {
		_spec.SetField(order.FieldTraderID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ClientOrderID(); ok {
		_spec.SetField(order.FieldClientOrderID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExchangeOrderID(); ok {
		_spec.SetField(order.FieldExchangeOrderID, field.TypeString, value)
	}
	if _u.mutation.ExchangeOrderIDCleared() {
		_spec.ClearField(order.FieldExchangeOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.ExchangeID(); ok {
		_spec.SetField(order.FieldExchangeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StrategyID(); ok {
		_spec.SetField(order.FieldStrategyID, field.TypeUUID, value)
	}
	if _u.mutation.StrategyIDCleared() {
		_spec.ClearField(order.FieldStrategyID, field.TypeUUID)
	}
	if value, ok := _u.mutation.PositionID(); ok {
		_spec.SetField(order.FieldPositionID, field.TypeUUID, value)
	}
	if _u.mutation.PositionIDCleared() {
		_spec.ClearField(order.FieldPositionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Pair(); ok {
		_spec.SetField(order.FieldPair, field.TypeString, value)
	}
	if value, ok := _u.mutation.Side(); ok {
		_spec.SetField(order.FieldSide, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(order.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(order.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(order.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(order.FieldPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(order.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FilledQuantity(); ok {
		_spec.SetField(order.FieldFilledQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFilledQuantity(); ok {
		_spec.AddField(order.FieldFilledQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuoteQuantity(); ok {
		_spec.SetField(order.FieldQuoteQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuoteQuantity(); ok {
		_spec.AddField(order.FieldQuoteQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fee(); ok {
		_spec.SetField(order.FieldFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFee(); ok {
		_spec.AddField(order.FieldFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeAsset(); ok {
		_spec.SetField(order.FieldFeeAsset, field.TypeString, value)
	}
	if _u.mutation.FeeAssetCleared() {
		_spec.ClearField(order.FieldFeeAsset, field.TypeString)
	}
	if value, ok := _u.mutation.IsManual(); ok {
		_spec.SetField(order.FieldIsManual, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PlacedAtUtc(); ok {
		_spec.SetField(order.FieldPlacedAtUtc, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(order.FieldVersion, field.TypeUUID, value)
	}
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
