// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"tradex/internal/infra/ent/order"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Order is the model entity for the Order schema.
type Order struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TraderID holds the value of the "trader_id" field.
	TraderID uuid.UUID `json:"trader_id,omitempty"`
	// ClientOrderID holds the value of the "client_order_id" field.
	ClientOrderID uuid.UUID `json:"client_order_id,omitempty"`
	// ExchangeOrderID holds the value of the "exchange_order_id" field.
	ExchangeOrderID *string `json:"exchange_order_id,omitempty"`
	// ExchangeID holds the value of the "exchange_id" field.
	ExchangeID uuid.UUID `json:"exchange_id,omitempty"`
	// StrategyID holds the value of the "strategy_id" field.
	StrategyID *uuid.UUID `json:"strategy_id,omitempty"`
	// PositionID holds the value of the "position_id" field.
	PositionID *uuid.UUID `json:"position_id,omitempty"`
	// Pair holds the value of the "pair" field.
	Pair string `json:"pair,omitempty"`
	// Side holds the value of the "side" field.
	Side string `json:"side,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Price holds the value of the "price" field.
	Price *float64 `json:"price,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// FilledQuantity holds the value of the "filled_quantity" field.
	FilledQuantity float64 `json:"filled_quantity,omitempty"`
	// QuoteQuantity holds the value of the "quote_quantity" field.
	QuoteQuantity float64 `json:"quote_quantity,omitempty"`
	// Fee holds the value of the "fee" field.
	Fee float64 `json:"fee,omitempty"`
	// FeeAsset holds the value of the "fee_asset" field.
	FeeAsset *string `json:"fee_asset,omitempty"`
	// IsManual holds the value of the "is_manual" field.
	IsManual bool `json:"is_manual,omitempty"`
	// PlacedAtUtc holds the value of the "placed_at_utc" field.
	PlacedAtUtc time.Time `json:"placed_at_utc,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Version holds the value of the "version" field.
	Version      uuid.UUID `json:"version,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Order) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case order.FieldStrategyID, order.FieldPositionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case order.FieldIsManual:
			values[i] = new(sql.NullBool)
		case order.FieldPrice, order.FieldQuantity, order.FieldFilledQuantity, order.FieldQuoteQuantity, order.FieldFee:
			values[i] = new(sql.NullFloat64)
		case order.FieldExchangeOrderID, order.FieldPair, order.FieldSide, order.FieldType, order.FieldStatus, order.FieldFeeAsset:
			values[i] = new(sql.NullString)
		case order.FieldPlacedAtUtc, order.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case order.FieldID, order.FieldTraderID, order.FieldClientOrderID, order.FieldExchangeID, order.FieldVersion:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Order fields.
func (_m *Order) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case order.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case order.FieldTraderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field trader_id", values[i])
			} else if value != nil {
				_m.TraderID = *value
			}
		case order.FieldClientOrderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_order_id", values[i])
			} else if value != nil {
				_m.ClientOrderID = *value
			}
		case order.FieldExchangeOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_order_id", values[i])
			} else if value.Valid {
				_m.ExchangeOrderID = new(string)
				*_m.ExchangeOrderID = value.String
			}
		case order.FieldExchangeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_id", values[i])
			} else if value != nil {
				_m.ExchangeID = *value
			}
		case order.FieldStrategyID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_id", values[i])
			} else if value.Valid {
				_m.StrategyID = new(uuid.UUID)
				*_m.StrategyID = *value.S.(*uuid.UUID)
			}
		case order.FieldPositionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field position_id", values[i])
			} else if value.Valid {
				_m.PositionID = new(uuid.UUID)
				*_m.PositionID = *value.S.(*uuid.UUID)
			}
		case order.FieldPair:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pair", values[i])
			} else if value.Valid {
				_m.Pair = value.String
			}
		case order.FieldSide:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field side", values[i])
			} else if value.Valid {
				_m.Side = value.String
			}
		case order.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case order.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case order.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = new(float64)
				*_m.Price = value.Float64
			}
		case order.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case order.FieldFilledQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field filled_quantity", values[i])
			} else if value.Valid {
				_m.FilledQuantity = value.Float64
			}
		case order.FieldQuoteQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quote_quantity", values[i])
			} else if value.Valid {
				_m.QuoteQuantity = value.Float64
			}
		case order.FieldFee:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee", values[i])
			} else if value.Valid {
				_m.Fee = value.Float64
			}
		case order.FieldFeeAsset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fee_asset", values[i])
			} else if value.Valid {
				_m.FeeAsset = new(string)
				*_m.FeeAsset = value.String
			}
		case order.FieldIsManual:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_manual", values[i])
			} else if value.Valid {
				_m.IsManual = value.Bool
			}
		case order.FieldPlacedAtUtc:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field placed_at_utc", values[i])
			} else if value.Valid {
				_m.PlacedAtUtc = value.Time
			}
		case order.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case order.FieldVersion:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value != nil {
				_m.Version = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Order.
// This includes values selected through modifiers, order, etc.
func (_m *Order) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Order.
// Note that you need to call Order.Unwrap() before calling this method if this Order
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Order) Update() *OrderUpdateOne {
	return NewOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Order entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Order) Unwrap() *Order {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Order is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Order) String() string {
	var builder strings.Builder
	builder.WriteString("Order(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("trader_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TraderID))
	builder.WriteString(", ")
	builder.WriteString("client_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientOrderID))
	builder.WriteString(", ")
	if v := _m.ExchangeOrderID; v != nil {
		builder.WriteString("exchange_order_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("exchange_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExchangeID))
	builder.WriteString(", ")
	if v := _m.StrategyID; v != nil {
		builder.WriteString("strategy_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PositionID; v != nil {
		builder.WriteString("position_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("pair=")
	builder.WriteString(_m.Pair)
	builder.WriteString(", ")
	builder.WriteString("side=")
	builder.WriteString(_m.Side)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Price; v != nil {
		builder.WriteString("price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("filled_quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.FilledQuantity))
	builder.WriteString(", ")
	builder.WriteString("quote_quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuoteQuantity))
	builder.WriteString(", ")
	builder.WriteString("fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.Fee))
	builder.WriteString(", ")
	if v := _m.FeeAsset; v != nil {
		builder.WriteString("fee_asset=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_manual=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsManual))
	builder.WriteString(", ")
	builder.WriteString("placed_at_utc=")
	builder.WriteString(_m.PlacedAtUtc.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// Orders is a parsable slice of Order.
type Orders []*Order
