// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"tradex/internal/infra/ent/position"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Position is the model entity for the Position schema.
type Position struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TraderID holds the value of the "trader_id" field.
	TraderID uuid.UUID `json:"trader_id,omitempty"`
	// ExchangeID holds the value of the "exchange_id" field.
	ExchangeID uuid.UUID `json:"exchange_id,omitempty"`
	// StrategyID holds the value of the "strategy_id" field.
	StrategyID uuid.UUID `json:"strategy_id,omitempty"`
	// OpeningOrderID holds the value of the "opening_order_id" field.
	OpeningOrderID *uuid.UUID `json:"opening_order_id,omitempty"`
	// Pair holds the value of the "pair" field.
	Pair string `json:"pair,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// EntryPrice holds the value of the "entry_price" field.
	EntryPrice float64 `json:"entry_price,omitempty"`
	// CurrentPrice holds the value of the "current_price" field.
	CurrentPrice float64 `json:"current_price,omitempty"`
	// UnrealizedPnl holds the value of the "unrealized_pnl" field.
	UnrealizedPnl float64 `json:"unrealized_pnl,omitempty"`
	// RealizedPnl holds the value of the "realized_pnl" field.
	RealizedPnl float64 `json:"realized_pnl,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// OpenedAtUtc holds the value of the "opened_at_utc" field.
	OpenedAtUtc time.Time `json:"opened_at_utc,omitempty"`
	// ClosedAtUtc holds the value of the "closed_at_utc" field.
	ClosedAtUtc *time.Time `json:"closed_at_utc,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Version holds the value of the "version" field.
	Version      uuid.UUID `json:"version,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Position) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case position.FieldOpeningOrderID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case position.FieldQuantity, position.FieldEntryPrice, position.FieldCurrentPrice, position.FieldUnrealizedPnl, position.FieldRealizedPnl:
			values[i] = new(sql.NullFloat64)
		case position.FieldPair, position.FieldStatus:
			values[i] = new(sql.NullString)
		case position.FieldOpenedAtUtc, position.FieldClosedAtUtc, position.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case position.FieldID, position.FieldTraderID, position.FieldExchangeID, position.FieldStrategyID, position.FieldVersion:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Position fields.
func (_m *Position) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case position.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case position.FieldTraderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field trader_id", values[i])
			} else if value != nil {
				_m.TraderID = *value
			}
		case position.FieldExchangeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_id", values[i])
			} else if value != nil {
				_m.ExchangeID = *value
			}
		case position.FieldStrategyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_id", values[i])
			} else if value != nil {
				_m.StrategyID = *value
			}
		case position.FieldOpeningOrderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field opening_order_id", values[i])
			} else if value.Valid {
				_m.OpeningOrderID = new(uuid.UUID)
				*_m.OpeningOrderID = *value.S.(*uuid.UUID)
			}
		case position.FieldPair:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pair", values[i])
			} else if value.Valid {
				_m.Pair = value.String
			}
		case position.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case position.FieldEntryPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field entry_price", values[i])
			} else if value.Valid {
				_m.EntryPrice = value.Float64
			}
		case position.FieldCurrentPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field current_price", values[i])
			} else if value.Valid {
				_m.CurrentPrice = value.Float64
			}
		case position.FieldUnrealizedPnl:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unrealized_pnl", values[i])
			} else if value.Valid {
				_m.UnrealizedPnl = value.Float64
			}
		case position.FieldRealizedPnl:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field realized_pnl", values[i])
			} else if value.Valid {
				_m.RealizedPnl = value.Float64
			}
		case position.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case position.FieldOpenedAtUtc:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field opened_at_utc", values[i])
			} else if value.Valid {
				_m.OpenedAtUtc = value.Time
			}
		case position.FieldClosedAtUtc:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at_utc", values[i])
			} else if value.Valid {
				_m.ClosedAtUtc = new(time.Time)
				*_m.ClosedAtUtc = value.Time
			}
		case position.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case position.FieldVersion:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value != nil {
				_m.Version = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Position.
// This includes values selected through modifiers, order, etc.
func (_m *Position) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Position.
// Note that you need to call Position.Unwrap() before calling this method if this Position
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Position) Update() *PositionUpdateOne {
	return NewPositionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Position entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Position) Unwrap() *Position {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Position is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Position) String() string {
	var builder strings.Builder
	builder.WriteString("Position(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("trader_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TraderID))
	builder.WriteString(", ")
	builder.WriteString("exchange_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExchangeID))
	builder.WriteString(", ")
	builder.WriteString("strategy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StrategyID))
	builder.WriteString(", ")
	if v := _m.OpeningOrderID; v != nil {
		builder.WriteString("opening_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("pair=")
	builder.WriteString(_m.Pair)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("entry_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntryPrice))
	builder.WriteString(", ")
	builder.WriteString("current_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentPrice))
	builder.WriteString(", ")
	builder.WriteString("unrealized_pnl=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnrealizedPnl))
	builder.WriteString(", ")
	builder.WriteString("realized_pnl=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealizedPnl))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("opened_at_utc=")
	builder.WriteString(_m.OpenedAtUtc.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClosedAtUtc; v != nil {
		builder.WriteString("closed_at_utc=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// Positions is a parsable slice of Position.
type Positions []*Position
