// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tradex/internal/infra/ent/strategybinding"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StrategyBindingCreate is the builder for creating a StrategyBinding entity.
type StrategyBindingCreate struct {
	config
	mutation *StrategyBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetStrategyID sets the "strategy_id" field.
func (_c *StrategyBindingCreate) SetStrategyID(v uuid.UUID) *StrategyBindingCreate {
	_c.mutation.SetStrategyID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *StrategyBindingCreate) SetName(v string) *StrategyBindingCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTraderID sets the "trader_id" field.
func (_c *StrategyBindingCreate) SetTraderID(v uuid.UUID) *StrategyBindingCreate {
	_c.mutation.SetTraderID(v)
	return _c
}

// SetExchangeID sets the "exchange_id" field.
func (_c *StrategyBindingCreate) SetExchangeID(v uuid.UUID) *StrategyBindingCreate {
	_c.mutation.SetExchangeID(v)
	return _c
}

// SetPairs sets the "pairs" field.
func (_c *StrategyBindingCreate) SetPairs(v string) *StrategyBindingCreate {
	_c.mutation.SetPairs(v)
	return _c
}

// SetTimeframe sets the "timeframe" field.
func (_c *StrategyBindingCreate) SetTimeframe(v string) *StrategyBindingCreate {
	_c.mutation.SetTimeframe(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *StrategyBindingCreate) SetStatus(v string) *StrategyBindingCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *StrategyBindingCreate) SetCreatedBy(v uuid.UUID) *StrategyBindingCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StrategyBindingCreate) SetCreatedAt(v time.Time) *StrategyBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StrategyBindingCreate) SetUpdatedAt(v time.Time) *StrategyBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *StrategyBindingCreate) SetID(v uuid.UUID) *StrategyBindingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StrategyBindingCreate) SetNillableID(v *uuid.UUID) *StrategyBindingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the StrategyBindingMutation object of the builder.
func (_c *StrategyBindingCreate) Mutation() *StrategyBindingMutation {
	return _c.mutation
}

// Save creates the StrategyBinding in the database.
func (_c *StrategyBindingCreate) Save(ctx context.Context) (*StrategyBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StrategyBindingCreate) SaveX(ctx context.Context) *StrategyBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StrategyBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StrategyBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StrategyBindingCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := strategybinding.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StrategyBindingCreate) check() error {
	if _, ok := _c.mutation.StrategyID(); !ok {
		return &ValidationError{Name: "strategy_id", err: errors.New(`ent: missing required field "StrategyBinding.strategy_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "StrategyBinding.name"`)}
	}
	if _, ok := _c.mutation.TraderID(); !ok {
		return &ValidationError{Name: "trader_id", err: errors.New(`ent: missing required field "StrategyBinding.trader_id"`)}
	}
	if _, ok := _c.mutation.ExchangeID(); !ok {
		return &ValidationError{Name: "exchange_id", err: errors.New(`ent: missing required field "StrategyBinding.exchange_id"`)}
	}
	if _, ok := _c.mutation.Pairs(); !ok {
		return &ValidationError{Name: "pairs", err: errors.New(`ent: missing required field "StrategyBinding.pairs"`)}
	}
	if _, ok := _c.mutation.Timeframe(); !ok {
		return &ValidationError{Name: "timeframe", err: errors.New(`ent: missing required field "StrategyBinding.timeframe"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StrategyBinding.status"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "StrategyBinding.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StrategyBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StrategyBinding.updated_at"`)}
	}
	return nil
}

func (_c *StrategyBindingCreate) sqlSave(ctx context.Context) (*StrategyBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StrategyBindingCreate) createSpec() (*StrategyBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &StrategyBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(strategybinding.Table, sqlgraph.NewFieldSpec(strategybinding.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.StrategyID(); ok {
		_spec.SetField(strategybinding.FieldStrategyID, field.TypeUUID, value)
		_node.StrategyID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(strategybinding.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TraderID(); ok {
		_spec.SetField(strategybinding.FieldTraderID, field.TypeUUID, value)
		_node.TraderID = value
	}
	if value, ok := _c.mutation.ExchangeID(); ok {
		_spec.SetField(strategybinding.FieldExchangeID, field.TypeUUID, value)
		_node.ExchangeID = value
	}
	if value, ok := _c.mutation.Pairs(); ok {
		_spec.SetField(strategybinding.FieldPairs, field.TypeString, value)
		_node.Pairs = value
	}
	if value, ok := _c.mutation.Timeframe(); ok {
		_spec.SetField(strategybinding.FieldTimeframe, field.TypeString, value)
		_node.Timeframe = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(strategybinding.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(strategybinding.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(strategybinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(strategybinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StrategyBinding.Create().
//		SetStrategyID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StrategyBindingUpsert) {
//			SetStrategyID(v+v).
//		}).
//		Exec(ctx)
func (_c *StrategyBindingCreate) OnConflict(opts ...sql.ConflictOption) *StrategyBindingUpsertOne {
	_c.conflict = opts
	return &StrategyBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StrategyBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StrategyBindingCreate) OnConflictColumns(columns ...string) *StrategyBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StrategyBindingUpsertOne{
		create: _c,
	}
}

type (
	// StrategyBindingUpsertOne is the builder for "upsert"-ing
	//  one StrategyBinding node.
	StrategyBindingUpsertOne struct {
		create *StrategyBindingCreate
	}

	// StrategyBindingUpsert is the "OnConflict" setter.
	StrategyBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetStrategyID sets the "strategy_id" field.
func (u *StrategyBindingUpsert) SetStrategyID(v uuid.UUID) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldStrategyID, v)
	return u
}

// UpdateStrategyID sets the "strategy_id" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdateStrategyID() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldStrategyID)
	return u
}

// SetName sets the "name" field.
func (u *StrategyBindingUpsert) SetName(v string) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdateName() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldName)
	return u
}

// SetTraderID sets the "trader_id" field.
func (u *StrategyBindingUpsert) SetTraderID(v uuid.UUID) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldTraderID, v)
	return u
}

// UpdateTraderID sets the "trader_id" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdateTraderID() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldTraderID)
	return u
}

// SetExchangeID sets the "exchange_id" field.
func (u *StrategyBindingUpsert) SetExchangeID(v uuid.UUID) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldExchangeID, v)
	return u
}

// UpdateExchangeID sets the "exchange_id" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdateExchangeID() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldExchangeID)
	return u
}

// SetPairs sets the "pairs" field.
func (u *StrategyBindingUpsert) SetPairs(v string) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldPairs, v)
	return u
}

// UpdatePairs sets the "pairs" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdatePairs() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldPairs)
	return u
}

// SetTimeframe sets the "timeframe" field.
func (u *StrategyBindingUpsert) SetTimeframe(v string) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldTimeframe, v)
	return u
}

// UpdateTimeframe sets the "timeframe" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdateTimeframe() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldTimeframe)
	return u
}

// SetStatus sets the "status" field.
func (u *StrategyBindingUpsert) SetStatus(v string) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdateStatus() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldStatus)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *StrategyBindingUpsert) SetCreatedBy(v uuid.UUID) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdateCreatedBy() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldCreatedBy)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *StrategyBindingUpsert) SetCreatedAt(v time.Time) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdateCreatedAt() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StrategyBindingUpsert) SetUpdatedAt(v time.Time) *StrategyBindingUpsert {
	u.Set(strategybinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StrategyBindingUpsert) UpdateUpdatedAt() *StrategyBindingUpsert {
	u.SetExcluded(strategybinding.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.StrategyBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(strategybinding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StrategyBindingUpsertOne) UpdateNewValues() *StrategyBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(strategybinding.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StrategyBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StrategyBindingUpsertOne) Ignore() *StrategyBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StrategyBindingUpsertOne) DoNothing() *StrategyBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StrategyBindingCreate.OnConflict
// documentation for more info.
func (u *StrategyBindingUpsertOne) Update(set func(*StrategyBindingUpsert)) *StrategyBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StrategyBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetStrategyID sets the "strategy_id" field.
func (u *StrategyBindingUpsertOne) SetStrategyID(v uuid.UUID) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetStrategyID(v)
	})
}

// UpdateStrategyID sets the "strategy_id" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdateStrategyID() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateStrategyID()
	})
}

// SetName sets the "name" field.
func (u *StrategyBindingUpsertOne) SetName(v string) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdateName() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateName()
	})
}

// SetTraderID sets the "trader_id" field.
func (u *StrategyBindingUpsertOne) SetTraderID(v uuid.UUID) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetTraderID(v)
	})
}

// UpdateTraderID sets the "trader_id" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdateTraderID() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateTraderID()
	})
}

// SetExchangeID sets the "exchange_id" field.
func (u *StrategyBindingUpsertOne) SetExchangeID(v uuid.UUID) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetExchangeID(v)
	})
}

// UpdateExchangeID sets the "exchange_id" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdateExchangeID() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateExchangeID()
	})
}

// SetPairs sets the "pairs" field.
func (u *StrategyBindingUpsertOne) SetPairs(v string) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetPairs(v)
	})
}

// UpdatePairs sets the "pairs" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdatePairs() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdatePairs()
	})
}

// SetTimeframe sets the "timeframe" field.
func (u *StrategyBindingUpsertOne) SetTimeframe(v string) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetTimeframe(v)
	})
}

// UpdateTimeframe sets the "timeframe" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdateTimeframe() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateTimeframe()
	})
}

// SetStatus sets the "status" field.
func (u *StrategyBindingUpsertOne) SetStatus(v string) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdateStatus() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *StrategyBindingUpsertOne) SetCreatedBy(v uuid.UUID) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdateCreatedBy() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *StrategyBindingUpsertOne) SetCreatedAt(v time.Time) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdateCreatedAt() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StrategyBindingUpsertOne) SetUpdatedAt(v time.Time) *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StrategyBindingUpsertOne) UpdateUpdatedAt() *StrategyBindingUpsertOne {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *StrategyBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StrategyBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StrategyBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StrategyBindingUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: StrategyBindingUpsertOne.ID is not supported by MySQL driver. Use StrategyBindingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StrategyBindingUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StrategyBindingCreateBulk is the builder for creating many StrategyBinding entities in bulk.
type StrategyBindingCreateBulk struct {
	config
	err      error
	builders []*StrategyBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the StrategyBinding entities in the database.
func (_c *StrategyBindingCreateBulk) Save(ctx context.Context) ([]*StrategyBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StrategyBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StrategyBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StrategyBindingCreateBulk) SaveX(ctx context.Context) []*StrategyBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StrategyBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StrategyBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StrategyBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StrategyBindingUpsert) {
//			SetStrategyID(v+v).
//		}).
//		Exec(ctx)
func (_c *StrategyBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *StrategyBindingUpsertBulk {
	_c.conflict = opts
	return &StrategyBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StrategyBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StrategyBindingCreateBulk) OnConflictColumns(columns ...string) *StrategyBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StrategyBindingUpsertBulk{
		create: _c,
	}
}

// StrategyBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of StrategyBinding nodes.
type StrategyBindingUpsertBulk struct {
	create *StrategyBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.StrategyBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(strategybinding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StrategyBindingUpsertBulk) UpdateNewValues() *StrategyBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(strategybinding.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StrategyBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StrategyBindingUpsertBulk) Ignore() *StrategyBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StrategyBindingUpsertBulk) DoNothing() *StrategyBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StrategyBindingCreateBulk.OnConflict
// documentation for more info.
func (u *StrategyBindingUpsertBulk) Update(set func(*StrategyBindingUpsert)) *StrategyBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StrategyBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetStrategyID sets the "strategy_id" field.
func (u *StrategyBindingUpsertBulk) SetStrategyID(v uuid.UUID) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetStrategyID(v)
	})
}

// UpdateStrategyID sets the "strategy_id" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdateStrategyID() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateStrategyID()
	})
}

// SetName sets the "name" field.
func (u *StrategyBindingUpsertBulk) SetName(v string) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdateName() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateName()
	})
}

// SetTraderID sets the "trader_id" field.
func (u *StrategyBindingUpsertBulk) SetTraderID(v uuid.UUID) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetTraderID(v)
	})
}

// UpdateTraderID sets the "trader_id" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdateTraderID() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateTraderID()
	})
}

// SetExchangeID sets the "exchange_id" field.
func (u *StrategyBindingUpsertBulk) SetExchangeID(v uuid.UUID) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetExchangeID(v)
	})
}

// UpdateExchangeID sets the "exchange_id" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdateExchangeID() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateExchangeID()
	})
}

// SetPairs sets the "pairs" field.
func (u *StrategyBindingUpsertBulk) SetPairs(v string) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetPairs(v)
	})
}

// UpdatePairs sets the "pairs" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdatePairs() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdatePairs()
	})
}

// SetTimeframe sets the "timeframe" field.
func (u *StrategyBindingUpsertBulk) SetTimeframe(v string) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetTimeframe(v)
	})
}

// UpdateTimeframe sets the "timeframe" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdateTimeframe() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateTimeframe()
	})
}

// SetStatus sets the "status" field.
func (u *StrategyBindingUpsertBulk) SetStatus(v string) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdateStatus() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *StrategyBindingUpsertBulk) SetCreatedBy(v uuid.UUID) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdateCreatedBy() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *StrategyBindingUpsertBulk) SetCreatedAt(v time.Time) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdateCreatedAt() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StrategyBindingUpsertBulk) SetUpdatedAt(v time.Time) *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StrategyBindingUpsertBulk) UpdateUpdatedAt() *StrategyBindingUpsertBulk {
	return u.Update(func(s *StrategyBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *StrategyBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StrategyBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StrategyBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StrategyBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
