// Code generated by ent, DO NOT EDIT.

package strategy

import (
	"time"
	"tradex/internal/infrastructure/persistence/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldName, v))
}

// EntryCondition applies equality check predicate on the "entry_condition" field. It's identical to EntryConditionEQ.
func EntryCondition(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldEntryCondition, v))
}

// ExitCondition applies equality check predicate on the "exit_condition" field. It's identical to ExitConditionEQ.
func ExitCondition(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExitCondition, v))
}

// ExecutionRule applies equality check predicate on the "execution_rule" field. It's identical to ExecutionRuleEQ.
func ExecutionRule(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExecutionRule, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldVersion, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldName, v))
}

// EntryConditionEQ applies the EQ predicate on the "entry_condition" field.
func EntryConditionEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldEntryCondition, v))
}

// EntryConditionNEQ applies the NEQ predicate on the "entry_condition" field.
func EntryConditionNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldEntryCondition, v))
}

// EntryConditionIn applies the In predicate on the "entry_condition" field.
func EntryConditionIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldEntryCondition, vs...))
}

// EntryConditionNotIn applies the NotIn predicate on the "entry_condition" field.
func EntryConditionNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldEntryCondition, vs...))
}

// EntryConditionGT applies the GT predicate on the "entry_condition" field.
func EntryConditionGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldEntryCondition, v))
}

// EntryConditionGTE applies the GTE predicate on the "entry_condition" field.
func EntryConditionGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldEntryCondition, v))
}

// EntryConditionLT applies the LT predicate on the "entry_condition" field.
func EntryConditionLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldEntryCondition, v))
}

// EntryConditionLTE applies the LTE predicate on the "entry_condition" field.
func EntryConditionLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldEntryCondition, v))
}

// EntryConditionContains applies the Contains predicate on the "entry_condition" field.
func EntryConditionContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldEntryCondition, v))
}

// EntryConditionHasPrefix applies the HasPrefix predicate on the "entry_condition" field.
func EntryConditionHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldEntryCondition, v))
}

// EntryConditionHasSuffix applies the HasSuffix predicate on the "entry_condition" field.
func EntryConditionHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldEntryCondition, v))
}

// EntryConditionIsNil applies the IsNil predicate on the "entry_condition" field.
func EntryConditionIsNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldIsNull(FieldEntryCondition))
}

// EntryConditionNotNil applies the NotNil predicate on the "entry_condition" field.
func EntryConditionNotNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldNotNull(FieldEntryCondition))
}

// EntryConditionEqualFold applies the EqualFold predicate on the "entry_condition" field.
func EntryConditionEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldEntryCondition, v))
}

// EntryConditionContainsFold applies the ContainsFold predicate on the "entry_condition" field.
func EntryConditionContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldEntryCondition, v))
}

// ExitConditionEQ applies the EQ predicate on the "exit_condition" field.
func ExitConditionEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExitCondition, v))
}

// ExitConditionNEQ applies the NEQ predicate on the "exit_condition" field.
func ExitConditionNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldExitCondition, v))
}

// ExitConditionIn applies the In predicate on the "exit_condition" field.
func ExitConditionIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldExitCondition, vs...))
}

// ExitConditionNotIn applies the NotIn predicate on the "exit_condition" field.
func ExitConditionNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldExitCondition, vs...))
}

// ExitConditionGT applies the GT predicate on the "exit_condition" field.
func ExitConditionGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldExitCondition, v))
}

// ExitConditionGTE applies the GTE predicate on the "exit_condition" field.
func ExitConditionGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldExitCondition, v))
}

// ExitConditionLT applies the LT predicate on the "exit_condition" field.
func ExitConditionLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldExitCondition, v))
}

// ExitConditionLTE applies the LTE predicate on the "exit_condition" field.
func ExitConditionLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldExitCondition, v))
}

// ExitConditionContains applies the Contains predicate on the "exit_condition" field.
func ExitConditionContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldExitCondition, v))
}

// ExitConditionHasPrefix applies the HasPrefix predicate on the "exit_condition" field.
func ExitConditionHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldExitCondition, v))
}

// ExitConditionHasSuffix applies the HasSuffix predicate on the "exit_condition" field.
func ExitConditionHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldExitCondition, v))
}

// ExitConditionIsNil applies the IsNil predicate on the "exit_condition" field.
func ExitConditionIsNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldIsNull(FieldExitCondition))
}

// ExitConditionNotNil applies the NotNil predicate on the "exit_condition" field.
func ExitConditionNotNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldNotNull(FieldExitCondition))
}

// ExitConditionEqualFold applies the EqualFold predicate on the "exit_condition" field.
func ExitConditionEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldExitCondition, v))
}

// ExitConditionContainsFold applies the ContainsFold predicate on the "exit_condition" field.
func ExitConditionContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldExitCondition, v))
}

// ExecutionRuleEQ applies the EQ predicate on the "execution_rule" field.
func ExecutionRuleEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExecutionRule, v))
}

// ExecutionRuleNEQ applies the NEQ predicate on the "execution_rule" field.
func ExecutionRuleNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldExecutionRule, v))
}

// ExecutionRuleIn applies the In predicate on the "execution_rule" field.
func ExecutionRuleIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldExecutionRule, vs...))
}

// ExecutionRuleNotIn applies the NotIn predicate on the "execution_rule" field.
func ExecutionRuleNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldExecutionRule, vs...))
}

// ExecutionRuleGT applies the GT predicate on the "execution_rule" field.
func ExecutionRuleGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldExecutionRule, v))
}

// ExecutionRuleGTE applies the GTE predicate on the "execution_rule" field.
func ExecutionRuleGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldExecutionRule, v))
}

// ExecutionRuleLT applies the LT predicate on the "execution_rule" field.
func ExecutionRuleLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldExecutionRule, v))
}

// ExecutionRuleLTE applies the LTE predicate on the "execution_rule" field.
func ExecutionRuleLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldExecutionRule, v))
}

// ExecutionRuleContains applies the Contains predicate on the "execution_rule" field.
func ExecutionRuleContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldExecutionRule, v))
}

// ExecutionRuleHasPrefix applies the HasPrefix predicate on the "execution_rule" field.
func ExecutionRuleHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldExecutionRule, v))
}

// ExecutionRuleHasSuffix applies the HasSuffix predicate on the "execution_rule" field.
func ExecutionRuleHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldExecutionRule, v))
}

// ExecutionRuleIsNil applies the IsNil predicate on the "execution_rule" field.
func ExecutionRuleIsNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldIsNull(FieldExecutionRule))
}

// ExecutionRuleNotNil applies the NotNil predicate on the "execution_rule" field.
func ExecutionRuleNotNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldNotNull(FieldExecutionRule))
}

// ExecutionRuleEqualFold applies the EqualFold predicate on the "execution_rule" field.
func ExecutionRuleEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldExecutionRule, v))
}

// ExecutionRuleContainsFold applies the ContainsFold predicate on the "execution_rule" field.
func ExecutionRuleContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldExecutionRule, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldVersion, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Strategy) predicate.Strategy {
	return predicate.Strategy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Strategy) predicate.Strategy {
	return predicate.Strategy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Strategy) predicate.Strategy {
	return predicate.Strategy(sql.NotPredicates(p))
}
