// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tradex/backend-go/internal/infra/persistence/ent/backtestresult"
	"github.com/tradex/backend-go/internal/infra/persistence/ent/predicate"
)

// BacktestResultDelete is the builder for deleting a BacktestResult entity.
type BacktestResultDelete struct {
	config
	hooks    []Hook
	mutation *BacktestResultMutation
}

// Where appends a list predicates to the BacktestResultDelete builder.
func (_d *BacktestResultDelete) Where(ps ...predicate.BacktestResult) *BacktestResultDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BacktestResultDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BacktestResultDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BacktestResultDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(backtestresult.Table, sqlgraph.NewFieldSpec(backtestresult.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BacktestResultDeleteOne is the builder for deleting a single BacktestResult entity.
type BacktestResultDeleteOne struct {
	_d *BacktestResultDelete
}

// Where appends a list predicates to the BacktestResultDelete builder.
func (_d *BacktestResultDeleteOne) Where(ps ...predicate.BacktestResult) *BacktestResultDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BacktestResultDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{backtestresult.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BacktestResultDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
