// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tradex/backend-go/internal/infra/persistence/ent/predicate"
	"github.com/tradex/backend-go/internal/infra/persistence/ent/strategy"
)

// StrategyUpdate is the builder for updating Strategy entities.
type StrategyUpdate struct {
	config
	hooks    []Hook
	mutation *StrategyMutation
}

// Where appends a list predicates to the StrategyUpdate builder.
func (_u *StrategyUpdate) Where(ps ...predicate.Strategy) *StrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *StrategyUpdate) SetName(v string) *StrategyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableName(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEntryCondition sets the "entry_condition" field.
func (_u *StrategyUpdate) SetEntryCondition(v string) *StrategyUpdate {
	_u.mutation.SetEntryCondition(v)
	return _u
}

// SetNillableEntryCondition sets the "entry_condition" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableEntryCondition(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetEntryCondition(*v)
	}
	return _u
}

// ClearEntryCondition clears the value of the "entry_condition" field.
func (_u *StrategyUpdate) ClearEntryCondition() *StrategyUpdate {
	_u.mutation.ClearEntryCondition()
	return _u
}

// SetExitCondition sets the "exit_condition" field.
func (_u *StrategyUpdate) SetExitCondition(v string) *StrategyUpdate {
	_u.mutation.SetExitCondition(v)
	return _u
}

// SetNillableExitCondition sets the "exit_condition" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableExitCondition(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetExitCondition(*v)
	}
	return _u
}

// ClearExitCondition clears the value of the "exit_condition" field.
func (_u *StrategyUpdate) ClearExitCondition() *StrategyUpdate {
	_u.mutation.ClearExitCondition()
	return _u
}

// SetExecutionRule sets the "execution_rule" field.
func (_u *StrategyUpdate) SetExecutionRule(v string) *StrategyUpdate {
	_u.mutation.SetExecutionRule(v)
	return _u
}

// SetNillableExecutionRule sets the "execution_rule" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableExecutionRule(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetExecutionRule(*v)
	}
	return _u
}

// ClearExecutionRule clears the value of the "execution_rule" field.
func (_u *StrategyUpdate) ClearExecutionRule() *StrategyUpdate {
	_u.mutation.ClearExecutionRule()
	return _u
}

// SetExchangeID sets the "exchange_id" field.
func (_u *StrategyUpdate) SetExchangeID(v string) *StrategyUpdate {
	_u.mutation.SetExchangeID(v)
	return _u
}

// SetNillableExchangeID sets the "exchange_id" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableExchangeID(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetExchangeID(*v)
	}
	return _u
}

// SetPair sets the "pair" field.
func (_u *StrategyUpdate) SetPair(v string) *StrategyUpdate {
	_u.mutation.SetPair(v)
	return _u
}

// SetNillablePair sets the "pair" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillablePair(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetPair(*v)
	}
	return _u
}

// SetTimeframe sets the "timeframe" field.
func (_u *StrategyUpdate) SetTimeframe(v string) *StrategyUpdate {
	_u.mutation.SetTimeframe(v)
	return _u
}

// SetNillableTimeframe sets the "timeframe" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableTimeframe(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetTimeframe(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *StrategyUpdate) SetIsActive(v bool) *StrategyUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableIsActive(v *bool) *StrategyUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the StrategyMutation object of the builder.
func (_u *StrategyUpdate) Mutation() *StrategyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StrategyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(strategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryCondition(); ok {
		_spec.SetField(strategy.FieldEntryCondition, field.TypeString, value)
	}
	if _u.mutation.EntryConditionCleared() {
		_spec.ClearField(strategy.FieldEntryCondition, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCondition(); ok {
		_spec.SetField(strategy.FieldExitCondition, field.TypeString, value)
	}
	if _u.mutation.ExitConditionCleared() {
		_spec.ClearField(strategy.FieldExitCondition, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutionRule(); ok {
		_spec.SetField(strategy.FieldExecutionRule, field.TypeString, value)
	}
	if _u.mutation.ExecutionRuleCleared() {
		_spec.ClearField(strategy.FieldExecutionRule, field.TypeString)
	}
	if value, ok := _u.mutation.ExchangeID(); ok {
		_spec.SetField(strategy.FieldExchangeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pair(); ok {
		_spec.SetField(strategy.FieldPair, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timeframe(); ok {
		_spec.SetField(strategy.FieldTimeframe, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(strategy.FieldIsActive, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StrategyUpdateOne is the builder for updating a single Strategy entity.
type StrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StrategyMutation
}

// SetName sets the "name" field.
func (_u *StrategyUpdateOne) SetName(v string) *StrategyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableName(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEntryCondition sets the "entry_condition" field.
func (_u *StrategyUpdateOne) SetEntryCondition(v string) *StrategyUpdateOne {
	_u.mutation.SetEntryCondition(v)
	return _u
}

// SetNillableEntryCondition sets the "entry_condition" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableEntryCondition(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetEntryCondition(*v)
	}
	return _u
}

// ClearEntryCondition clears the value of the "entry_condition" field.
func (_u *StrategyUpdateOne) ClearEntryCondition() *StrategyUpdateOne {
	_u.mutation.ClearEntryCondition()
	return _u
}

// SetExitCondition sets the "exit_condition" field.
func (_u *StrategyUpdateOne) SetExitCondition(v string) *StrategyUpdateOne {
	_u.mutation.SetExitCondition(v)
	return _u
}

// SetNillableExitCondition sets the "exit_condition" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableExitCondition(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetExitCondition(*v)
	}
	return _u
}

// ClearExitCondition clears the value of the "exit_condition" field.
func (_u *StrategyUpdateOne) ClearExitCondition() *StrategyUpdateOne {
	_u.mutation.ClearExitCondition()
	return _u
}

// SetExecutionRule sets the "execution_rule" field.
func (_u *StrategyUpdateOne) SetExecutionRule(v string) *StrategyUpdateOne {
	_u.mutation.SetExecutionRule(v)
	return _u
}

// SetNillableExecutionRule sets the "execution_rule" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableExecutionRule(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetExecutionRule(*v)
	}
	return _u
}

// ClearExecutionRule clears the value of the "execution_rule" field.
func (_u *StrategyUpdateOne) ClearExecutionRule() *StrategyUpdateOne {
	_u.mutation.ClearExecutionRule()
	return _u
}

// SetExchangeID sets the "exchange_id" field.
func (_u *StrategyUpdateOne) SetExchangeID(v string) *StrategyUpdateOne {
	_u.mutation.SetExchangeID(v)
	return _u
}

// SetNillableExchangeID sets the "exchange_id" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableExchangeID(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetExchangeID(*v)
	}
	return _u
}

// SetPair sets the "pair" field.
func (_u *StrategyUpdateOne) SetPair(v string) *StrategyUpdateOne {
	_u.mutation.SetPair(v)
	return _u
}

// SetNillablePair sets the "pair" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillablePair(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetPair(*v)
	}
	return _u
}

// SetTimeframe sets the "timeframe" field.
func (_u *StrategyUpdateOne) SetTimeframe(v string) *StrategyUpdateOne {
	_u.mutation.SetTimeframe(v)
	return _u
}

// SetNillableTimeframe sets the "timeframe" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableTimeframe(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetTimeframe(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *StrategyUpdateOne) SetIsActive(v bool) *StrategyUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableIsActive(v *bool) *StrategyUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the StrategyMutation object of the builder.
func (_u *StrategyUpdateOne) Mutation() *StrategyMutation {
	return _u.mutation
}

// Where appends a list predicates to the StrategyUpdate builder.
func (_u *StrategyUpdateOne) Where(ps ...predicate.Strategy) *StrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StrategyUpdateOne) Select(field string, fields ...string) *StrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Strategy entity.
func (_u *StrategyUpdateOne) Save(ctx context.Context) (*Strategy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyUpdateOne) SaveX(ctx context.Context) *Strategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StrategyUpdateOne) sqlSave(ctx context.Context) (_node *Strategy, err error) {
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Strategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, strategy.FieldID)
		for _, f := range fields {
			if !strategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != strategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(strategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryCondition(); ok {
		_spec.SetField(strategy.FieldEntryCondition, field.TypeString, value)
	}
	if _u.mutation.EntryConditionCleared() {
		_spec.ClearField(strategy.FieldEntryCondition, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCondition(); ok {
		_spec.SetField(strategy.FieldExitCondition, field.TypeString, value)
	}
	if _u.mutation.ExitConditionCleared() {
		_spec.ClearField(strategy.FieldExitCondition, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutionRule(); ok {
		_spec.SetField(strategy.FieldExecutionRule, field.TypeString, value)
	}
	if _u.mutation.ExecutionRuleCleared() {
		_spec.ClearField(strategy.FieldExecutionRule, field.TypeString)
	}
	if value, ok := _u.mutation.ExchangeID(); ok {
		_spec.SetField(strategy.FieldExchangeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pair(); ok {
		_spec.SetField(strategy.FieldPair, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timeframe(); ok {
		_spec.SetField(strategy.FieldTimeframe, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(strategy.FieldIsActive, field.TypeBool, value)
	}
	_node = &Strategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
