// Code generated by ent, DO NOT EDIT.

package backtestklineanalysis

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the backtestklineanalysis type in the database.
	Label = "backtest_kline_analysis"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldKlineIndex holds the string denoting the kline_index field in the database.
	FieldKlineIndex = "kline_index"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldOpen holds the string denoting the open field in the database.
	FieldOpen = "open"
	// FieldHigh holds the string denoting the high field in the database.
	FieldHigh = "high"
	// FieldLow holds the string denoting the low field in the database.
	FieldLow = "low"
	// FieldClose holds the string denoting the close field in the database.
	FieldClose = "close"
	// FieldVolume holds the string denoting the volume field in the database.
	FieldVolume = "volume"
	// FieldIndicatorValues holds the string denoting the indicator_values field in the database.
	FieldIndicatorValues = "indicator_values"
	// FieldEntryConditionResult holds the string denoting the entry_condition_result field in the database.
	FieldEntryConditionResult = "entry_condition_result"
	// FieldExitConditionResult holds the string denoting the exit_condition_result field in the database.
	FieldExitConditionResult = "exit_condition_result"
	// FieldInPosition holds the string denoting the in_position field in the database.
	FieldInPosition = "in_position"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldPositionValue holds the string denoting the position_value field in the database.
	FieldPositionValue = "position_value"
	// FieldPositionPnl holds the string denoting the position_pnl field in the database.
	FieldPositionPnl = "position_pnl"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the backtestklineanalysis in the database.
	Table = "backtest_kline_analyses"
)

// Columns holds all SQL columns for backtestklineanalysis fields.
var Columns = []string{
	FieldID,
	FieldTaskID,
	FieldKlineIndex,
	FieldTimestamp,
	FieldOpen,
	FieldHigh,
	FieldLow,
	FieldClose,
	FieldVolume,
	FieldIndicatorValues,
	FieldEntryConditionResult,
	FieldExitConditionResult,
	FieldInPosition,
	FieldAction,
	FieldPositionValue,
	FieldPositionPnl,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInPosition holds the default value on creation for the "in_position" field.
	DefaultInPosition bool
	// DefaultAction holds the default value on creation for the "action" field.
	DefaultAction string
	// DefaultPositionValue holds the default value on creation for the "position_value" field.
	DefaultPositionValue float64
	// DefaultPositionPnl holds the default value on creation for the "position_pnl" field.
	DefaultPositionPnl float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the BacktestKlineAnalysis queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByKlineIndex orders the results by the kline_index field.
func ByKlineIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKlineIndex, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByOpen orders the results by the open field.
func ByOpen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpen, opts...).ToFunc()
}

// ByHigh orders the results by the high field.
func ByHigh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHigh, opts...).ToFunc()
}

// ByLow orders the results by the low field.
func ByLow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLow, opts...).ToFunc()
}

// ByClose orders the results by the close field.
func ByClose(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClose, opts...).ToFunc()
}

// ByVolume orders the results by the volume field.
func ByVolume(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVolume, opts...).ToFunc()
}

// ByInPosition orders the results by the in_position field.
func ByInPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInPosition, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByPositionValue orders the results by the position_value field.
func ByPositionValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionValue, opts...).ToFunc()
}

// ByPositionPnl orders the results by the position_pnl field.
func ByPositionPnl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionPnl, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
