// Code generated by ent, DO NOT EDIT.

package exchangeorderhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the exchangeorderhistory type in the database.
	Label = "exchange_order_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExchangeID holds the string denoting the exchange_id field in the database.
	FieldExchangeID = "exchange_id"
	// FieldPair holds the string denoting the pair field in the database.
	FieldPair = "pair"
	// FieldSide holds the string denoting the side field in the database.
	FieldSide = "side"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldFilledQuantity holds the string denoting the filled_quantity field in the database.
	FieldFilledQuantity = "filled_quantity"
	// FieldExchangeOrderID holds the string denoting the exchange_order_id field in the database.
	FieldExchangeOrderID = "exchange_order_id"
	// FieldPlacedAt holds the string denoting the placed_at field in the database.
	FieldPlacedAt = "placed_at"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// Table holds the table name of the exchangeorderhistory in the database.
	Table = "exchange_order_histories"
)

// Columns holds all SQL columns for exchangeorderhistory fields.
var Columns = []string{
	FieldID,
	FieldExchangeID,
	FieldPair,
	FieldSide,
	FieldType,
	FieldStatus,
	FieldPrice,
	FieldQuantity,
	FieldFilledQuantity,
	FieldExchangeOrderID,
	FieldPlacedAt,
	FieldSyncedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPair holds the default value on creation for the "pair" field.
	DefaultPair string
	// DefaultSide holds the default value on creation for the "side" field.
	DefaultSide string
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity float64
	// DefaultFilledQuantity holds the default value on creation for the "filled_quantity" field.
	DefaultFilledQuantity float64
	// DefaultExchangeOrderID holds the default value on creation for the "exchange_order_id" field.
	DefaultExchangeOrderID string
	// DefaultSyncedAt holds the default value on creation for the "synced_at" field.
	DefaultSyncedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ExchangeOrderHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByExchangeID orders the results by the exchange_id field.
func ByExchangeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeID, opts...).ToFunc()
}

// ByPair orders the results by the pair field.
func ByPair(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPair, opts...).ToFunc()
}

// BySide orders the results by the side field.
func BySide(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSide, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByFilledQuantity orders the results by the filled_quantity field.
func ByFilledQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilledQuantity, opts...).ToFunc()
}

// ByExchangeOrderID orders the results by the exchange_order_id field.
func ByExchangeOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeOrderID, opts...).ToFunc()
}

// ByPlacedAt orders the results by the placed_at field.
func ByPlacedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlacedAt, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}
