// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"tradex/internal/infrastructure/persistence/ent/strategy"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Strategy is the model entity for the Strategy schema.
type Strategy struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// EntryCondition holds the value of the "entry_condition" field.
	EntryCondition string `json:"entry_condition,omitempty"`
	// ExitCondition holds the value of the "exit_condition" field.
	ExitCondition string `json:"exit_condition,omitempty"`
	// ExecutionRule holds the value of the "execution_rule" field.
	ExecutionRule string `json:"execution_rule,omitempty"`
	// ExchangeID holds the value of the "exchange_id" field.
	ExchangeID string `json:"exchange_id,omitempty"`
	// Pair holds the value of the "pair" field.
	Pair string `json:"pair,omitempty"`
	// Timeframe holds the value of the "timeframe" field.
	Timeframe string `json:"timeframe,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive     bool `json:"is_active,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Strategy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case strategy.FieldIsActive:
			values[i] = new(sql.NullBool)
		case strategy.FieldName, strategy.FieldEntryCondition, strategy.FieldExitCondition, strategy.FieldExecutionRule, strategy.FieldExchangeID, strategy.FieldPair, strategy.FieldTimeframe:
			values[i] = new(sql.NullString)
		case strategy.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Strategy fields.
func (_m *Strategy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case strategy.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case strategy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case strategy.FieldEntryCondition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_condition", values[i])
			} else if value.Valid {
				_m.EntryCondition = value.String
			}
		case strategy.FieldExitCondition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exit_condition", values[i])
			} else if value.Valid {
				_m.ExitCondition = value.String
			}
		case strategy.FieldExecutionRule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_rule", values[i])
			} else if value.Valid {
				_m.ExecutionRule = value.String
			}
		case strategy.FieldExchangeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_id", values[i])
			} else if value.Valid {
				_m.ExchangeID = value.String
			}
		case strategy.FieldPair:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pair", values[i])
			} else if value.Valid {
				_m.Pair = value.String
			}
		case strategy.FieldTimeframe:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timeframe", values[i])
			} else if value.Valid {
				_m.Timeframe = value.String
			}
		case strategy.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Strategy.
// This includes values selected through modifiers, order, etc.
func (_m *Strategy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Strategy.
// Note that you need to call Strategy.Unwrap() before calling this method if this Strategy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Strategy) Update() *StrategyUpdateOne {
	return NewStrategyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Strategy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Strategy) Unwrap() *Strategy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Strategy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Strategy) String() string {
	var builder strings.Builder
	builder.WriteString("Strategy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("entry_condition=")
	builder.WriteString(_m.EntryCondition)
	builder.WriteString(", ")
	builder.WriteString("exit_condition=")
	builder.WriteString(_m.ExitCondition)
	builder.WriteString(", ")
	builder.WriteString("execution_rule=")
	builder.WriteString(_m.ExecutionRule)
	builder.WriteString(", ")
	builder.WriteString("exchange_id=")
	builder.WriteString(_m.ExchangeID)
	builder.WriteString(", ")
	builder.WriteString("pair=")
	builder.WriteString(_m.Pair)
	builder.WriteString(", ")
	builder.WriteString("timeframe=")
	builder.WriteString(_m.Timeframe)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// Strategies is a parsable slice of Strategy.
type Strategies []*Strategy
