using TradeX.Infrastructure.Casbin;

namespace TradeX.Tests.Infrastructure;

public class CasbinEnforcerTests
{
    private readonly CasbinEnforcer _enforcer = new();

    [Theory]
    [InlineData("superadmin", "/api/v1/traders", "GET", true)]
    [InlineData("superadmin", "/api/v1/traders", "POST", true)]
    [InlineData("superadmin", "/api/v1/users", "DELETE", true)]
    [InlineData("superadmin", "/api/v1/settings", "PUT", true)]
    [InlineData("superadmin", "/api/v1/traders/123/strategies/456/toggle", "POST", true)]
    [InlineData("superadmin", "/api/v1/system/emergency-stop", "POST", true)]
    [InlineData("superadmin", "/api/v1/orders/manual", "POST", true)]
    [InlineData("superadmin", "/api/v1/traders/123/strategies/456/backtests", "POST", true)]
    [InlineData("superadmin", "/api/v1/auth/mfa/setup", "POST", true)]
    [InlineData("admin", "/api/v1/traders", "GET", true)]
    [InlineData("admin", "/api/v1/traders", "POST", true)]
    [InlineData("admin", "/api/v1/traders/123", "PUT", true)]
    [InlineData("admin", "/api/v1/traders/123", "DELETE", true)]
    [InlineData("admin", "/api/v1/traders/123/exchanges", "GET", true)]
    [InlineData("admin", "/api/v1/traders/123/exchanges", "POST", true)]
    [InlineData("admin", "/api/v1/traders/123/exchanges/456", "DELETE", true)]
    [InlineData("admin", "/api/v1/traders/123/exchanges/456/test", "POST", true)]
    [InlineData("admin", "/api/v1/traders/123/exchanges/456/rules", "GET", true)]
    [InlineData("admin", "/api/v1/traders/123/strategies", "POST", true)]
    [InlineData("admin", "/api/v1/traders/123/strategies/456", "PUT", true)]
    [InlineData("admin", "/api/v1/traders/123/strategies/456/toggle", "POST", true)]
    [InlineData("admin", "/api/v1/backtests", "POST", true)]
    [InlineData("admin", "/api/v1/backtests/tasks", "GET", true)]
    [InlineData("admin", "/api/v1/backtests/tasks/789", "GET", true)]
    [InlineData("admin", "/api/v1/backtests/tasks/789/result", "GET", true)]
    [InlineData("admin", "/api/v1/backtests/tasks/789/analysis", "GET", true)]
    [InlineData("admin", "/api/v1/backtests/tasks/789/analysis/stream", "GET", true)]
    [InlineData("admin", "/api/v1/traders/123/strategies/456/backtests", "POST", true)]
    [InlineData("admin", "/api/v1/traders/123/strategies/456/backtests/tasks", "GET", true)]
    [InlineData("admin", "/api/v1/traders/123/strategies/456/backtests/tasks/789", "GET", true)]
    [InlineData("admin", "/api/v1/traders/123/strategies/456/backtests/tasks/789/result", "GET", true)]
    [InlineData("admin", "/api/v1/traders/123/positions", "GET", true)]
    [InlineData("admin", "/api/v1/users", "GET", true)]
    [InlineData("admin", "/api/v1/users", "POST", true)]
    [InlineData("admin", "/api/v1/users/123/role", "PUT", true)]
    [InlineData("admin", "/api/v1/audit-logs", "GET", true)]
    [InlineData("admin", "/api/v1/settings", "GET", true)]
    [InlineData("admin", "/api/v1/settings", "PUT", true)]
    [InlineData("admin", "/api/v1/system/emergency-stop", "POST", true)]
    [InlineData("admin", "/api/v1/notifications/channels", "GET", true)]
    [InlineData("admin", "/api/v1/notifications/channels/123", "DELETE", true)]
    [InlineData("admin", "/api/v1/dashboard/stats", "GET", true)]
    [InlineData("admin", "/api/v1/dashboard/summary", "GET", true)]
    [InlineData("admin", "/api/v1/orders/export", "GET", true)]
    [InlineData("admin", "/api/v1/traders/123/orders/manual", "POST", true)]
    [InlineData("admin", "/api/v1/auth/logout", "POST", true)]
    [InlineData("admin", "/api/v1/auth/mfa/setup", "POST", true)]
    [InlineData("admin", "/api/v1/auth/mfa/verify", "POST", true)]
    [InlineData("admin", "/api/v1/auth/send-recovery-codes", "POST", true)]
    [InlineData("operator", "/api/v1/traders", "GET", true)]
    [InlineData("operator", "/api/v1/traders/123", "GET", true)]
    [InlineData("operator", "/api/v1/traders/123/exchanges", "POST", true)]
    [InlineData("operator", "/api/v1/traders/123/exchanges/456", "DELETE", true)]
    [InlineData("operator", "/api/v1/traders/123/exchanges/456/test", "POST", true)]
    [InlineData("operator", "/api/v1/traders/123/exchanges/456/rules", "GET", true)]
    [InlineData("operator", "/api/v1/traders/123/strategies", "POST", true)]
    [InlineData("operator", "/api/v1/traders/123/strategies/456", "PUT", true)]
    [InlineData("operator", "/api/v1/traders/123/strategies/456/toggle", "POST", true)]
    [InlineData("operator", "/api/v1/backtests", "POST", true)]
    [InlineData("operator", "/api/v1/backtests/tasks", "GET", true)]
    [InlineData("operator", "/api/v1/backtests/tasks/789", "GET", true)]
    [InlineData("operator", "/api/v1/backtests/tasks/789/result", "GET", true)]
    [InlineData("operator", "/api/v1/backtests/tasks/789/analysis", "GET", true)]
    [InlineData("operator", "/api/v1/backtests/tasks/789/analysis/stream", "GET", true)]
    [InlineData("operator", "/api/v1/traders/123/strategies/456/backtests", "POST", true)]
    [InlineData("operator", "/api/v1/traders/123/strategies/456/backtests/tasks", "GET", true)]
    [InlineData("operator", "/api/v1/traders/123/strategies/456/backtests/tasks/789", "GET", true)]
    [InlineData("operator", "/api/v1/traders/123/strategies/456/backtests/tasks/789/result", "GET", true)]
    [InlineData("operator", "/api/v1/traders/123/orders/manual", "POST", true)]
    [InlineData("operator", "/api/v1/dashboard/stats", "GET", true)]
    [InlineData("operator", "/api/v1/dashboard/summary", "GET", true)]
    [InlineData("operator", "/api/v1/orders/export", "GET", true)]
    [InlineData("operator", "/api/v1/auth/logout", "POST", true)]
    [InlineData("operator", "/api/v1/auth/mfa/setup", "POST", true)]
    [InlineData("operator", "/api/v1/auth/mfa/verify", "POST", true)]
    [InlineData("operator", "/api/v1/auth/send-recovery-codes", "POST", true)]
    [InlineData("viewer", "/api/v1/traders", "GET", true)]
    [InlineData("viewer", "/api/v1/traders/123", "GET", true)]
    [InlineData("viewer", "/api/v1/traders/123/strategies", "GET", true)]
    [InlineData("viewer", "/api/v1/traders/123/positions", "GET", true)]
    [InlineData("viewer", "/api/v1/traders/123/orders", "GET", true)]
    [InlineData("viewer", "/api/v1/dashboard/stats", "GET", true)]
    [InlineData("viewer", "/api/v1/dashboard/summary", "GET", true)]
    [InlineData("viewer", "/api/v1/backtests/tasks", "GET", true)]
    [InlineData("viewer", "/api/v1/backtests/tasks/789", "GET", true)]
    [InlineData("viewer", "/api/v1/backtests/tasks/789/result", "GET", true)]
    [InlineData("viewer", "/api/v1/backtests/tasks/789/analysis", "GET", true)]
    [InlineData("viewer", "/api/v1/backtests/tasks/789/analysis/stream", "GET", true)]
    [InlineData("viewer", "/api/v1/traders/123/strategies/456/backtests/tasks", "GET", true)]
    [InlineData("viewer", "/api/v1/traders/123/strategies/456/backtests/tasks/789", "GET", true)]
    [InlineData("viewer", "/api/v1/traders/123/strategies/456/backtests/tasks/789/result", "GET", true)]
    [InlineData("viewer", "/api/v1/auth/logout", "POST", true)]
    [InlineData("viewer", "/api/v1/auth/mfa/setup", "POST", true)]
    [InlineData("viewer", "/api/v1/auth/mfa/verify", "POST", true)]
    public void Enforce_AllowedAction_ReturnsTrue(string role, string path, string method, bool expected)
    {
        var result = _enforcer.Enforce(role, path, method);
        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData("viewer", "/api/v1/traders", "POST", false)]
    [InlineData("viewer", "/api/v1/backtests", "POST", false)]
    [InlineData("viewer", "/api/v1/traders/123/exchanges", "POST", false)]
    [InlineData("viewer", "/api/v1/traders/123/strategies", "POST", false)]
    [InlineData("viewer", "/api/v1/traders/123/strategies/456/backtests", "POST", false)]
    [InlineData("viewer", "/api/v1/users", "GET", false)]
    [InlineData("viewer", "/api/v1/settings", "GET", false)]
    [InlineData("viewer", "/api/v1/audit-logs", "GET", false)]
    [InlineData("viewer", "/api/v1/auth/send-recovery-codes", "POST", false)]
    [InlineData("operator", "/api/v1/users", "GET", false)]
    [InlineData("operator", "/api/v1/users", "POST", false)]
    [InlineData("operator", "/api/v1/settings", "GET", false)]
    [InlineData("operator", "/api/v1/audit-logs", "GET", false)]
    [InlineData("operator", "/api/v1/traders", "POST", false)]
    [InlineData("operator", "/api/v1/traders/123", "PUT", false)]
    [InlineData("operator", "/api/v1/traders/123", "DELETE", false)]
    public void Enforce_DeniedAction_ReturnsFalse(string role, string path, string method, bool expected)
    {
        var result = _enforcer.Enforce(role, path, method);
        Assert.Equal(expected, result);
    }
}
