using TradeX.Infrastructure.Casbin;

namespace TradeX.Tests.Infrastructure;

public class CasbinEnforcerTests
{
    private readonly CasbinEnforcer _enforcer = new();

    [Theory]
    [InlineData("superadmin", "/api/traders", "GET", true)]
    [InlineData("superadmin", "/api/traders", "POST", true)]
    [InlineData("superadmin", "/api/users", "DELETE", true)]
    [InlineData("superadmin", "/api/settings", "PUT", true)]
    [InlineData("superadmin", "/api/traders/123/strategies/456/toggle", "POST", true)]
    [InlineData("superadmin", "/api/system/emergency-stop", "POST", true)]
    [InlineData("superadmin", "/api/orders/manual", "POST", true)]
    [InlineData("superadmin", "/api/traders/123/strategies/456/backtests", "POST", true)]
    [InlineData("superadmin", "/api/auth/mfa/setup", "POST", true)]
    [InlineData("admin", "/api/traders", "GET", true)]
    [InlineData("admin", "/api/traders", "POST", true)]
    [InlineData("admin", "/api/traders/123", "PUT", true)]
    [InlineData("admin", "/api/traders/123", "DELETE", true)]
    [InlineData("admin", "/api/traders/123/exchanges", "GET", true)]
    [InlineData("admin", "/api/traders/123/exchanges", "POST", true)]
    [InlineData("admin", "/api/traders/123/exchanges/456", "DELETE", true)]
    [InlineData("admin", "/api/traders/123/exchanges/456/test", "POST", true)]
    [InlineData("admin", "/api/traders/123/exchanges/456/rules", "GET", true)]
    [InlineData("admin", "/api/traders/123/strategies", "POST", true)]
    [InlineData("admin", "/api/traders/123/strategies/456", "PUT", true)]
    [InlineData("admin", "/api/traders/123/strategies/456/toggle", "POST", true)]
    [InlineData("admin", "/api/backtests", "POST", true)]
    [InlineData("admin", "/api/backtests/tasks", "GET", true)]
    [InlineData("admin", "/api/backtests/tasks/789", "GET", true)]
    [InlineData("admin", "/api/backtests/tasks/789/result", "GET", true)]
    [InlineData("admin", "/api/backtests/tasks/789/analysis", "GET", true)]
    [InlineData("admin", "/api/backtests/tasks/789/analysis/stream", "GET", true)]
    [InlineData("admin", "/api/traders/123/strategies/456/backtests", "POST", true)]
    [InlineData("admin", "/api/traders/123/strategies/456/backtests/tasks", "GET", true)]
    [InlineData("admin", "/api/traders/123/strategies/456/backtests/tasks/789", "GET", true)]
    [InlineData("admin", "/api/traders/123/strategies/456/backtests/tasks/789/result", "GET", true)]
    [InlineData("admin", "/api/traders/123/positions", "GET", true)]
    [InlineData("admin", "/api/users", "GET", true)]
    [InlineData("admin", "/api/users", "POST", true)]
    [InlineData("admin", "/api/users/123/role", "PUT", true)]
    [InlineData("admin", "/api/audit-logs", "GET", true)]
    [InlineData("admin", "/api/settings", "GET", true)]
    [InlineData("admin", "/api/settings", "PUT", true)]
    [InlineData("admin", "/api/system/emergency-stop", "POST", true)]
    [InlineData("admin", "/api/notifications/channels", "GET", true)]
    [InlineData("admin", "/api/notifications/channels/123", "DELETE", true)]
    [InlineData("admin", "/api/dashboard/stats", "GET", true)]
    [InlineData("admin", "/api/dashboard/summary", "GET", true)]
    [InlineData("admin", "/api/orders/export", "GET", true)]
    [InlineData("admin", "/api/traders/123/orders/manual", "POST", true)]
    [InlineData("admin", "/api/auth/logout", "POST", true)]
    [InlineData("admin", "/api/auth/mfa/setup", "POST", true)]
    [InlineData("admin", "/api/auth/mfa/verify", "POST", true)]
    [InlineData("admin", "/api/auth/send-recovery-codes", "POST", true)]
    [InlineData("operator", "/api/traders", "GET", true)]
    [InlineData("operator", "/api/traders/123", "GET", true)]
    [InlineData("operator", "/api/traders/123/exchanges", "POST", true)]
    [InlineData("operator", "/api/traders/123/exchanges/456", "DELETE", true)]
    [InlineData("operator", "/api/traders/123/exchanges/456/test", "POST", true)]
    [InlineData("operator", "/api/traders/123/exchanges/456/rules", "GET", true)]
    [InlineData("operator", "/api/traders/123/strategies", "POST", true)]
    [InlineData("operator", "/api/traders/123/strategies/456", "PUT", true)]
    [InlineData("operator", "/api/traders/123/strategies/456/toggle", "POST", true)]
    [InlineData("operator", "/api/backtests", "POST", true)]
    [InlineData("operator", "/api/backtests/tasks", "GET", true)]
    [InlineData("operator", "/api/backtests/tasks/789", "GET", true)]
    [InlineData("operator", "/api/backtests/tasks/789/result", "GET", true)]
    [InlineData("operator", "/api/backtests/tasks/789/analysis", "GET", true)]
    [InlineData("operator", "/api/backtests/tasks/789/analysis/stream", "GET", true)]
    [InlineData("operator", "/api/traders/123/strategies/456/backtests", "POST", true)]
    [InlineData("operator", "/api/traders/123/strategies/456/backtests/tasks", "GET", true)]
    [InlineData("operator", "/api/traders/123/strategies/456/backtests/tasks/789", "GET", true)]
    [InlineData("operator", "/api/traders/123/strategies/456/backtests/tasks/789/result", "GET", true)]
    [InlineData("operator", "/api/traders/123/orders/manual", "POST", true)]
    [InlineData("operator", "/api/dashboard/stats", "GET", true)]
    [InlineData("operator", "/api/dashboard/summary", "GET", true)]
    [InlineData("operator", "/api/orders/export", "GET", true)]
    [InlineData("operator", "/api/auth/logout", "POST", true)]
    [InlineData("operator", "/api/auth/mfa/setup", "POST", true)]
    [InlineData("operator", "/api/auth/mfa/verify", "POST", true)]
    [InlineData("operator", "/api/auth/send-recovery-codes", "POST", true)]
    [InlineData("viewer", "/api/traders", "GET", true)]
    [InlineData("viewer", "/api/traders/123", "GET", true)]
    [InlineData("viewer", "/api/traders/123/strategies", "GET", true)]
    [InlineData("viewer", "/api/traders/123/positions", "GET", true)]
    [InlineData("viewer", "/api/traders/123/orders", "GET", true)]
    [InlineData("viewer", "/api/dashboard/stats", "GET", true)]
    [InlineData("viewer", "/api/dashboard/summary", "GET", true)]
    [InlineData("viewer", "/api/backtests/tasks", "GET", true)]
    [InlineData("viewer", "/api/backtests/tasks/789", "GET", true)]
    [InlineData("viewer", "/api/backtests/tasks/789/result", "GET", true)]
    [InlineData("viewer", "/api/backtests/tasks/789/analysis", "GET", true)]
    [InlineData("viewer", "/api/backtests/tasks/789/analysis/stream", "GET", true)]
    [InlineData("viewer", "/api/traders/123/strategies/456/backtests/tasks", "GET", true)]
    [InlineData("viewer", "/api/traders/123/strategies/456/backtests/tasks/789", "GET", true)]
    [InlineData("viewer", "/api/traders/123/strategies/456/backtests/tasks/789/result", "GET", true)]
    [InlineData("viewer", "/api/auth/logout", "POST", true)]
    [InlineData("viewer", "/api/auth/mfa/setup", "POST", true)]
    [InlineData("viewer", "/api/auth/mfa/verify", "POST", true)]
    public void Enforce_AllowedAction_ReturnsTrue(string role, string path, string method, bool expected)
    {
        var result = _enforcer.Enforce(role, path, method);
        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData("viewer", "/api/traders", "POST", false)]
    [InlineData("viewer", "/api/backtests", "POST", false)]
    [InlineData("viewer", "/api/traders/123/exchanges", "POST", false)]
    [InlineData("viewer", "/api/traders/123/strategies", "POST", false)]
    [InlineData("viewer", "/api/traders/123/strategies/456/backtests", "POST", false)]
    [InlineData("viewer", "/api/users", "GET", false)]
    [InlineData("viewer", "/api/settings", "GET", false)]
    [InlineData("viewer", "/api/audit-logs", "GET", false)]
    [InlineData("viewer", "/api/auth/send-recovery-codes", "POST", false)]
    [InlineData("operator", "/api/users", "GET", false)]
    [InlineData("operator", "/api/users", "POST", false)]
    [InlineData("operator", "/api/settings", "GET", false)]
    [InlineData("operator", "/api/audit-logs", "GET", false)]
    [InlineData("operator", "/api/traders", "POST", false)]
    [InlineData("operator", "/api/traders/123", "PUT", false)]
    [InlineData("operator", "/api/traders/123", "DELETE", false)]
    public void Enforce_DeniedAction_ReturnsFalse(string role, string path, string method, bool expected)
    {
        var result = _enforcer.Enforce(role, path, method);
        Assert.Equal(expected, result);
    }
}
