// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeX.Infrastructure.Data;

#nullable disable

namespace TradeX.Infrastructure.Migrations
{
    [DbContext(typeof(TradeXDbContext))]
    partial class TradeXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradeX.Core.Models.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.BacktestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AnnualizedReturnPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("annualized_return_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<decimal>("FinalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("final_value");

                    b.Property<decimal>("InitialCapital")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_capital");

                    b.Property<decimal>("MaxDrawdownPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("max_drawdown_percent");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pair");

                    b.Property<decimal>("ProfitLossRatio")
                        .HasColumnType("numeric")
                        .HasColumnName("profit_loss_ratio");

                    b.Property<decimal>("SharpeRatio")
                        .HasColumnType("numeric")
                        .HasColumnName("sharpe_ratio");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_name");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeframe");

                    b.Property<decimal>("TotalReturnPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("total_return_percent");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer")
                        .HasColumnName("total_trades");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric")
                        .HasColumnName("win_rate");

                    b.HasKey("Id")
                        .HasName("pk_backtest_results");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_backtest_results_task_id");

                    b.ToTable("backtest_results", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.BacktestTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<decimal>("InitialCapital")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_capital");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pair");

                    b.Property<string>("Phase")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phase");

                    b.Property<decimal?>("PositionSize")
                        .HasColumnType("numeric")
                        .HasColumnName("position_size");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("strategy_name");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("timeframe");

                    b.HasKey("Id")
                        .HasName("pk_backtest_tasks");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_backtest_tasks_exchange_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_backtest_tasks_status");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("ix_backtest_tasks_strategy_id");

                    b.ToTable("backtest_tasks", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.Exchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_key_encrypted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_tested_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PassphraseEncrypted")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("passphrase_encrypted");

                    b.Property<string>("SecretKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_key_encrypted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TestResult")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("test_result");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exchanges");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_exchanges_name");

                    b.ToTable("exchanges", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.ExchangeOrderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<string>("ExchangeOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exchange_order_id");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("filled_quantity");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pair");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_exchange_order_histories");

                    b.HasIndex("ExchangeId", "ExchangeOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_exchange_order_histories_exchange_id_order_id");

                    b.HasIndex("ExchangeId", "PlacedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_exchange_order_histories_exchange_id_placed_at");

                    b.ToTable("exchange_order_histories", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.ExchangePairRuleSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<decimal>("MinNotional")
                        .HasColumnType("numeric")
                        .HasColumnName("min_notional");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("min_quantity");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("pair");

                    b.Property<int>("PricePrecision")
                        .HasColumnType("integer")
                        .HasColumnName("price_precision");

                    b.Property<int>("QuantityPrecision")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_precision");

                    b.Property<decimal>("StepSize")
                        .HasColumnType("numeric")
                        .HasColumnName("step_size");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("numeric")
                        .HasColumnName("tick_size");

                    b.HasKey("Id")
                        .HasName("pk_exchange_pair_rules");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_exchange_pair_rules_exchange_id");

                    b.ToTable("exchange_pair_rules", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.MfaSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mfa_secrets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mfa_secrets_user_id");

                    b.ToTable("mfa_secrets", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_encrypted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_tested_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_channels");

                    b.ToTable("notification_channels", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_order_id");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<string>("ExchangeOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exchange_order_id");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("fee");

                    b.Property<string>("FeeAsset")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fee_asset");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("filled_quantity");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pair");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at_utc");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("QuoteQuantity")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("quote_quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("trader_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_client_order_id");

                    b.HasIndex("ExchangeOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_exchange_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.HasIndex("TraderId")
                        .HasDatabaseName("ix_orders_trader_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.Pair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("base_asset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("quote_asset");

                    b.HasKey("Id")
                        .HasName("pk_pairs");

                    b.HasIndex("ExchangeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pairs_exchange_id_name");

                    b.ToTable("pairs", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("current_price");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("entry_price");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<Guid?>("OpeningOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("opening_order_id");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pair");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RealizedPnl")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("realized_pnl");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("trader_id");

                    b.Property<decimal>("UnrealizedPnl")
                        .HasColumnType("decimal(28,12)")
                        .HasColumnName("unrealized_pnl");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("OpeningOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_positions_opening_order_id")
                        .HasFilter("opening_order_id IS NOT NULL");

                    b.HasIndex("TraderId", "Status")
                        .HasDatabaseName("ix_positions_trader_id_status");

                    b.HasIndex("ExchangeId", "Pair", "Status")
                        .HasDatabaseName("ix_positions_exchange_id_pair_status");

                    b.HasIndex("StrategyId", "Pair", "Status")
                        .HasDatabaseName("ix_positions_strategy_id_pair_status");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.RecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recovery_codes");

                    b.HasIndex("UserId", "Code")
                        .HasDatabaseName("ix_recovery_codes_user_id_code");

                    b.ToTable("recovery_codes", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EntryCondition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_condition");

                    b.Property<string>("ExecutionRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("execution_rule");

                    b.Property<string>("ExitCondition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exit_condition");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_strategies");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_strategies_name");

                    b.ToTable("strategies", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.StrategyBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Pairs")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pairs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("timeframe");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("trader_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_strategy_bindings");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_strategy_bindings_status");

                    b.ToTable("strategy_bindings", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_system_configs");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_system_configs_key");

                    b.ToTable("system_configs", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.Trader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("avatar_color");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Style")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("style");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_traders");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_traders_user_id_name");

                    b.ToTable("traders", (string)null);
                });

            modelBuilder.Entity("TradeX.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mfa_enabled");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("MfaSecretEncrypted")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("mfa_secret_encrypted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RecoveryCodesJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("recovery_codes_json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TradeX.Infrastructure.Data.Entities.BacktestKlineAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<decimal?>("AvgEntryPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_entry_price");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric")
                        .HasColumnName("close");

                    b.Property<bool?>("EntryConditionResult")
                        .HasColumnType("boolean")
                        .HasColumnName("entry_condition_result");

                    b.Property<bool?>("ExitConditionResult")
                        .HasColumnType("boolean")
                        .HasColumnName("exit_condition_result");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric")
                        .HasColumnName("high");

                    b.Property<bool>("InPosition")
                        .HasColumnType("boolean")
                        .HasColumnName("in_position");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("IndicatorValues")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("indicator_values");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("open");

                    b.Property<decimal?>("PositionCost")
                        .HasColumnType("numeric")
                        .HasColumnName("position_cost");

                    b.Property<decimal?>("PositionPnl")
                        .HasColumnType("numeric")
                        .HasColumnName("position_pnl");

                    b.Property<decimal?>("PositionPnlPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("position_pnl_percent");

                    b.Property<decimal?>("PositionQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("position_quantity");

                    b.Property<decimal?>("PositionValue")
                        .HasColumnType("numeric")
                        .HasColumnName("position_value");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_backtest_kline_analyses");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_backtest_kline_analyses_task_id");

                    b.HasIndex("TaskId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_backtest_kline_analyses_task_id_index");

                    b.ToTable("backtest_kline_analyses", (string)null);
                });

            modelBuilder.Entity("TradeX.Infrastructure.Data.Entities.KlineCacheEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric")
                        .HasColumnName("close");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("open");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pair");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("timeframe");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_kline_cache");

                    b.HasIndex("ExchangeId", "Pair", "Timeframe", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("ix_kline_cache_exchange_id_pair_timeframe_timestamp");

                    b.ToTable("kline_cache", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
