linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell

linters-settings:
  errcheck:
    ignore: fmt:Fprintf

run:
  timeout: 5m
