// Code generated by ent, DO NOT EDIT.

package position

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the position type in the database.
	Label = "position"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTraderID holds the string denoting the trader_id field in the database.
	FieldTraderID = "trader_id"
	// FieldExchangeID holds the string denoting the exchange_id field in the database.
	FieldExchangeID = "exchange_id"
	// FieldStrategyID holds the string denoting the strategy_id field in the database.
	FieldStrategyID = "strategy_id"
	// FieldOpeningOrderID holds the string denoting the opening_order_id field in the database.
	FieldOpeningOrderID = "opening_order_id"
	// FieldPair holds the string denoting the pair field in the database.
	FieldPair = "pair"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldEntryPrice holds the string denoting the entry_price field in the database.
	FieldEntryPrice = "entry_price"
	// FieldCurrentPrice holds the string denoting the current_price field in the database.
	FieldCurrentPrice = "current_price"
	// FieldUnrealizedPnl holds the string denoting the unrealized_pnl field in the database.
	FieldUnrealizedPnl = "unrealized_pnl"
	// FieldRealizedPnl holds the string denoting the realized_pnl field in the database.
	FieldRealizedPnl = "realized_pnl"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOpenedAtUtc holds the string denoting the opened_at_utc field in the database.
	FieldOpenedAtUtc = "opened_at_utc"
	// FieldClosedAtUtc holds the string denoting the closed_at_utc field in the database.
	FieldClosedAtUtc = "closed_at_utc"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// Table holds the table name of the position in the database.
	Table = "positions"
)

// Columns holds all SQL columns for position fields.
var Columns = []string{
	FieldID,
	FieldTraderID,
	FieldExchangeID,
	FieldStrategyID,
	FieldOpeningOrderID,
	FieldPair,
	FieldQuantity,
	FieldEntryPrice,
	FieldCurrentPrice,
	FieldUnrealizedPnl,
	FieldRealizedPnl,
	FieldStatus,
	FieldOpenedAtUtc,
	FieldClosedAtUtc,
	FieldUpdatedAt,
	FieldVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Position queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTraderID orders the results by the trader_id field.
func ByTraderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraderID, opts...).ToFunc()
}

// ByExchangeID orders the results by the exchange_id field.
func ByExchangeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeID, opts...).ToFunc()
}

// ByStrategyID orders the results by the strategy_id field.
func ByStrategyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyID, opts...).ToFunc()
}

// ByOpeningOrderID orders the results by the opening_order_id field.
func ByOpeningOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpeningOrderID, opts...).ToFunc()
}

// ByPair orders the results by the pair field.
func ByPair(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPair, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByEntryPrice orders the results by the entry_price field.
func ByEntryPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryPrice, opts...).ToFunc()
}

// ByCurrentPrice orders the results by the current_price field.
func ByCurrentPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPrice, opts...).ToFunc()
}

// ByUnrealizedPnl orders the results by the unrealized_pnl field.
func ByUnrealizedPnl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnrealizedPnl, opts...).ToFunc()
}

// ByRealizedPnl orders the results by the realized_pnl field.
func ByRealizedPnl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealizedPnl, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOpenedAtUtc orders the results by the opened_at_utc field.
func ByOpenedAtUtc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenedAtUtc, opts...).ToFunc()
}

// ByClosedAtUtc orders the results by the closed_at_utc field.
func ByClosedAtUtc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAtUtc, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}
