// Code generated by ent, DO NOT EDIT.

package strategy

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tradex/backend-go/internal/infra/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldName, v))
}

// EntryCondition applies equality check predicate on the "entry_condition" field. It's identical to EntryConditionEQ.
func EntryCondition(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldEntryCondition, v))
}

// ExitCondition applies equality check predicate on the "exit_condition" field. It's identical to ExitConditionEQ.
func ExitCondition(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExitCondition, v))
}

// ExecutionRule applies equality check predicate on the "execution_rule" field. It's identical to ExecutionRuleEQ.
func ExecutionRule(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExecutionRule, v))
}

// ExchangeID applies equality check predicate on the "exchange_id" field. It's identical to ExchangeIDEQ.
func ExchangeID(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExchangeID, v))
}

// Pair applies equality check predicate on the "pair" field. It's identical to PairEQ.
func Pair(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldPair, v))
}

// Timeframe applies equality check predicate on the "timeframe" field. It's identical to TimeframeEQ.
func Timeframe(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldTimeframe, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldIsActive, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldName, v))
}

// EntryConditionEQ applies the EQ predicate on the "entry_condition" field.
func EntryConditionEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldEntryCondition, v))
}

// EntryConditionNEQ applies the NEQ predicate on the "entry_condition" field.
func EntryConditionNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldEntryCondition, v))
}

// EntryConditionIn applies the In predicate on the "entry_condition" field.
func EntryConditionIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldEntryCondition, vs...))
}

// EntryConditionNotIn applies the NotIn predicate on the "entry_condition" field.
func EntryConditionNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldEntryCondition, vs...))
}

// EntryConditionGT applies the GT predicate on the "entry_condition" field.
func EntryConditionGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldEntryCondition, v))
}

// EntryConditionGTE applies the GTE predicate on the "entry_condition" field.
func EntryConditionGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldEntryCondition, v))
}

// EntryConditionLT applies the LT predicate on the "entry_condition" field.
func EntryConditionLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldEntryCondition, v))
}

// EntryConditionLTE applies the LTE predicate on the "entry_condition" field.
func EntryConditionLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldEntryCondition, v))
}

// EntryConditionContains applies the Contains predicate on the "entry_condition" field.
func EntryConditionContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldEntryCondition, v))
}

// EntryConditionHasPrefix applies the HasPrefix predicate on the "entry_condition" field.
func EntryConditionHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldEntryCondition, v))
}

// EntryConditionHasSuffix applies the HasSuffix predicate on the "entry_condition" field.
func EntryConditionHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldEntryCondition, v))
}

// EntryConditionIsNil applies the IsNil predicate on the "entry_condition" field.
func EntryConditionIsNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldIsNull(FieldEntryCondition))
}

// EntryConditionNotNil applies the NotNil predicate on the "entry_condition" field.
func EntryConditionNotNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldNotNull(FieldEntryCondition))
}

// EntryConditionEqualFold applies the EqualFold predicate on the "entry_condition" field.
func EntryConditionEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldEntryCondition, v))
}

// EntryConditionContainsFold applies the ContainsFold predicate on the "entry_condition" field.
func EntryConditionContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldEntryCondition, v))
}

// ExitConditionEQ applies the EQ predicate on the "exit_condition" field.
func ExitConditionEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExitCondition, v))
}

// ExitConditionNEQ applies the NEQ predicate on the "exit_condition" field.
func ExitConditionNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldExitCondition, v))
}

// ExitConditionIn applies the In predicate on the "exit_condition" field.
func ExitConditionIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldExitCondition, vs...))
}

// ExitConditionNotIn applies the NotIn predicate on the "exit_condition" field.
func ExitConditionNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldExitCondition, vs...))
}

// ExitConditionGT applies the GT predicate on the "exit_condition" field.
func ExitConditionGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldExitCondition, v))
}

// ExitConditionGTE applies the GTE predicate on the "exit_condition" field.
func ExitConditionGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldExitCondition, v))
}

// ExitConditionLT applies the LT predicate on the "exit_condition" field.
func ExitConditionLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldExitCondition, v))
}

// ExitConditionLTE applies the LTE predicate on the "exit_condition" field.
func ExitConditionLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldExitCondition, v))
}

// ExitConditionContains applies the Contains predicate on the "exit_condition" field.
func ExitConditionContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldExitCondition, v))
}

// ExitConditionHasPrefix applies the HasPrefix predicate on the "exit_condition" field.
func ExitConditionHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldExitCondition, v))
}

// ExitConditionHasSuffix applies the HasSuffix predicate on the "exit_condition" field.
func ExitConditionHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldExitCondition, v))
}

// ExitConditionIsNil applies the IsNil predicate on the "exit_condition" field.
func ExitConditionIsNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldIsNull(FieldExitCondition))
}

// ExitConditionNotNil applies the NotNil predicate on the "exit_condition" field.
func ExitConditionNotNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldNotNull(FieldExitCondition))
}

// ExitConditionEqualFold applies the EqualFold predicate on the "exit_condition" field.
func ExitConditionEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldExitCondition, v))
}

// ExitConditionContainsFold applies the ContainsFold predicate on the "exit_condition" field.
func ExitConditionContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldExitCondition, v))
}

// ExecutionRuleEQ applies the EQ predicate on the "execution_rule" field.
func ExecutionRuleEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExecutionRule, v))
}

// ExecutionRuleNEQ applies the NEQ predicate on the "execution_rule" field.
func ExecutionRuleNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldExecutionRule, v))
}

// ExecutionRuleIn applies the In predicate on the "execution_rule" field.
func ExecutionRuleIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldExecutionRule, vs...))
}

// ExecutionRuleNotIn applies the NotIn predicate on the "execution_rule" field.
func ExecutionRuleNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldExecutionRule, vs...))
}

// ExecutionRuleGT applies the GT predicate on the "execution_rule" field.
func ExecutionRuleGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldExecutionRule, v))
}

// ExecutionRuleGTE applies the GTE predicate on the "execution_rule" field.
func ExecutionRuleGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldExecutionRule, v))
}

// ExecutionRuleLT applies the LT predicate on the "execution_rule" field.
func ExecutionRuleLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldExecutionRule, v))
}

// ExecutionRuleLTE applies the LTE predicate on the "execution_rule" field.
func ExecutionRuleLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldExecutionRule, v))
}

// ExecutionRuleContains applies the Contains predicate on the "execution_rule" field.
func ExecutionRuleContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldExecutionRule, v))
}

// ExecutionRuleHasPrefix applies the HasPrefix predicate on the "execution_rule" field.
func ExecutionRuleHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldExecutionRule, v))
}

// ExecutionRuleHasSuffix applies the HasSuffix predicate on the "execution_rule" field.
func ExecutionRuleHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldExecutionRule, v))
}

// ExecutionRuleIsNil applies the IsNil predicate on the "execution_rule" field.
func ExecutionRuleIsNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldIsNull(FieldExecutionRule))
}

// ExecutionRuleNotNil applies the NotNil predicate on the "execution_rule" field.
func ExecutionRuleNotNil() predicate.Strategy {
	return predicate.Strategy(sql.FieldNotNull(FieldExecutionRule))
}

// ExecutionRuleEqualFold applies the EqualFold predicate on the "execution_rule" field.
func ExecutionRuleEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldExecutionRule, v))
}

// ExecutionRuleContainsFold applies the ContainsFold predicate on the "execution_rule" field.
func ExecutionRuleContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldExecutionRule, v))
}

// ExchangeIDEQ applies the EQ predicate on the "exchange_id" field.
func ExchangeIDEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldExchangeID, v))
}

// ExchangeIDNEQ applies the NEQ predicate on the "exchange_id" field.
func ExchangeIDNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldExchangeID, v))
}

// ExchangeIDIn applies the In predicate on the "exchange_id" field.
func ExchangeIDIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldExchangeID, vs...))
}

// ExchangeIDNotIn applies the NotIn predicate on the "exchange_id" field.
func ExchangeIDNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldExchangeID, vs...))
}

// ExchangeIDGT applies the GT predicate on the "exchange_id" field.
func ExchangeIDGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldExchangeID, v))
}

// ExchangeIDGTE applies the GTE predicate on the "exchange_id" field.
func ExchangeIDGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldExchangeID, v))
}

// ExchangeIDLT applies the LT predicate on the "exchange_id" field.
func ExchangeIDLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldExchangeID, v))
}

// ExchangeIDLTE applies the LTE predicate on the "exchange_id" field.
func ExchangeIDLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldExchangeID, v))
}

// ExchangeIDContains applies the Contains predicate on the "exchange_id" field.
func ExchangeIDContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldExchangeID, v))
}

// ExchangeIDHasPrefix applies the HasPrefix predicate on the "exchange_id" field.
func ExchangeIDHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldExchangeID, v))
}

// ExchangeIDHasSuffix applies the HasSuffix predicate on the "exchange_id" field.
func ExchangeIDHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldExchangeID, v))
}

// ExchangeIDEqualFold applies the EqualFold predicate on the "exchange_id" field.
func ExchangeIDEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldExchangeID, v))
}

// ExchangeIDContainsFold applies the ContainsFold predicate on the "exchange_id" field.
func ExchangeIDContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldExchangeID, v))
}

// PairEQ applies the EQ predicate on the "pair" field.
func PairEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldPair, v))
}

// PairNEQ applies the NEQ predicate on the "pair" field.
func PairNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldPair, v))
}

// PairIn applies the In predicate on the "pair" field.
func PairIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldPair, vs...))
}

// PairNotIn applies the NotIn predicate on the "pair" field.
func PairNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldPair, vs...))
}

// PairGT applies the GT predicate on the "pair" field.
func PairGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldPair, v))
}

// PairGTE applies the GTE predicate on the "pair" field.
func PairGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldPair, v))
}

// PairLT applies the LT predicate on the "pair" field.
func PairLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldPair, v))
}

// PairLTE applies the LTE predicate on the "pair" field.
func PairLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldPair, v))
}

// PairContains applies the Contains predicate on the "pair" field.
func PairContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldPair, v))
}

// PairHasPrefix applies the HasPrefix predicate on the "pair" field.
func PairHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldPair, v))
}

// PairHasSuffix applies the HasSuffix predicate on the "pair" field.
func PairHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldPair, v))
}

// PairEqualFold applies the EqualFold predicate on the "pair" field.
func PairEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldPair, v))
}

// PairContainsFold applies the ContainsFold predicate on the "pair" field.
func PairContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldPair, v))
}

// TimeframeEQ applies the EQ predicate on the "timeframe" field.
func TimeframeEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldTimeframe, v))
}

// TimeframeNEQ applies the NEQ predicate on the "timeframe" field.
func TimeframeNEQ(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldTimeframe, v))
}

// TimeframeIn applies the In predicate on the "timeframe" field.
func TimeframeIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldIn(FieldTimeframe, vs...))
}

// TimeframeNotIn applies the NotIn predicate on the "timeframe" field.
func TimeframeNotIn(vs ...string) predicate.Strategy {
	return predicate.Strategy(sql.FieldNotIn(FieldTimeframe, vs...))
}

// TimeframeGT applies the GT predicate on the "timeframe" field.
func TimeframeGT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGT(FieldTimeframe, v))
}

// TimeframeGTE applies the GTE predicate on the "timeframe" field.
func TimeframeGTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldGTE(FieldTimeframe, v))
}

// TimeframeLT applies the LT predicate on the "timeframe" field.
func TimeframeLT(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLT(FieldTimeframe, v))
}

// TimeframeLTE applies the LTE predicate on the "timeframe" field.
func TimeframeLTE(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldLTE(FieldTimeframe, v))
}

// TimeframeContains applies the Contains predicate on the "timeframe" field.
func TimeframeContains(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContains(FieldTimeframe, v))
}

// TimeframeHasPrefix applies the HasPrefix predicate on the "timeframe" field.
func TimeframeHasPrefix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasPrefix(FieldTimeframe, v))
}

// TimeframeHasSuffix applies the HasSuffix predicate on the "timeframe" field.
func TimeframeHasSuffix(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldHasSuffix(FieldTimeframe, v))
}

// TimeframeEqualFold applies the EqualFold predicate on the "timeframe" field.
func TimeframeEqualFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldEqualFold(FieldTimeframe, v))
}

// TimeframeContainsFold applies the ContainsFold predicate on the "timeframe" field.
func TimeframeContainsFold(v string) predicate.Strategy {
	return predicate.Strategy(sql.FieldContainsFold(FieldTimeframe, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Strategy {
	return predicate.Strategy(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Strategy {
	return predicate.Strategy(sql.FieldNEQ(FieldIsActive, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Strategy) predicate.Strategy {
	return predicate.Strategy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Strategy) predicate.Strategy {
	return predicate.Strategy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Strategy) predicate.Strategy {
	return predicate.Strategy(sql.NotPredicates(p))
}
