// Code generated by ent, DO NOT EDIT.

package backtestresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the backtestresult type in the database.
	Label = "backtest_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStrategyName holds the string denoting the strategy_name field in the database.
	FieldStrategyName = "strategy_name"
	// FieldFinalValue holds the string denoting the final_value field in the database.
	FieldFinalValue = "final_value"
	// FieldTotalReturnPercent holds the string denoting the total_return_percent field in the database.
	FieldTotalReturnPercent = "total_return_percent"
	// FieldAnnualizedReturnPercent holds the string denoting the annualized_return_percent field in the database.
	FieldAnnualizedReturnPercent = "annualized_return_percent"
	// FieldMaxDrawdownPercent holds the string denoting the max_drawdown_percent field in the database.
	FieldMaxDrawdownPercent = "max_drawdown_percent"
	// FieldWinRate holds the string denoting the win_rate field in the database.
	FieldWinRate = "win_rate"
	// FieldSharpeRatio holds the string denoting the sharpe_ratio field in the database.
	FieldSharpeRatio = "sharpe_ratio"
	// FieldProfitLossRatio holds the string denoting the profit_loss_ratio field in the database.
	FieldProfitLossRatio = "profit_loss_ratio"
	// FieldTotalTrades holds the string denoting the total_trades field in the database.
	FieldTotalTrades = "total_trades"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTask holds the string denoting the task edge name in mutations.
	EdgeTask = "task"
	// Table holds the table name of the backtestresult in the database.
	Table = "backtest_results"
	// TaskTable is the table that holds the task relation/edge.
	TaskTable = "backtest_results"
	// TaskInverseTable is the table name for the BacktestTask entity.
	// It exists in this package in order to avoid circular dependency with the "backtesttask" package.
	TaskInverseTable = "backtest_tasks"
	// TaskColumn is the table column denoting the task relation/edge.
	TaskColumn = "result_id"
)

// Columns holds all SQL columns for backtestresult fields.
var Columns = []string{
	FieldID,
	FieldStrategyName,
	FieldFinalValue,
	FieldTotalReturnPercent,
	FieldAnnualizedReturnPercent,
	FieldMaxDrawdownPercent,
	FieldWinRate,
	FieldSharpeRatio,
	FieldProfitLossRatio,
	FieldTotalTrades,
	FieldDetails,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "backtest_results"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"result_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStrategyName holds the default value on creation for the "strategy_name" field.
	DefaultStrategyName string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the BacktestResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStrategyName orders the results by the strategy_name field.
func ByStrategyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyName, opts...).ToFunc()
}

// ByFinalValue orders the results by the final_value field.
func ByFinalValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalValue, opts...).ToFunc()
}

// ByTotalReturnPercent orders the results by the total_return_percent field.
func ByTotalReturnPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalReturnPercent, opts...).ToFunc()
}

// ByAnnualizedReturnPercent orders the results by the annualized_return_percent field.
func ByAnnualizedReturnPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnnualizedReturnPercent, opts...).ToFunc()
}

// ByMaxDrawdownPercent orders the results by the max_drawdown_percent field.
func ByMaxDrawdownPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxDrawdownPercent, opts...).ToFunc()
}

// ByWinRate orders the results by the win_rate field.
func ByWinRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWinRate, opts...).ToFunc()
}

// BySharpeRatio orders the results by the sharpe_ratio field.
func BySharpeRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSharpeRatio, opts...).ToFunc()
}

// ByProfitLossRatio orders the results by the profit_loss_ratio field.
func ByProfitLossRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfitLossRatio, opts...).ToFunc()
}

// ByTotalTrades orders the results by the total_trades field.
func ByTotalTrades(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTrades, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTaskField orders the results by task field.
func ByTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskStep(), sql.OrderByField(field, opts...))
	}
}
func newTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, TaskTable, TaskColumn),
	)
}
